### ISSUE TITLE
Scheduling WakeUp

### ISSUE THREAD

**Issue by bobcqld53** [seriousm4x/UpSnap#10]
Is it possible to set wake up schedule for multiple days - say every Sunday at 06:30 Hrs for rsync backup target.

**Comment by seriousm4x** [comment]
Not yet possible but I also thought about it. I plan on rewriting the frontend (and some of the backend) to make including new features more easy, but I need to find the time for it.

**Comment by bobcqld53** [comment]
Thanks for the feedback , look forward to new features when you get some spare time...
