### ISSUE TITLE
[REQUEST] Add OIDC Authentication

### ISSUE THREAD

**Issue by CygnusHyoga** [seriousm4x/UpSnap#103]
**The problem you currently have with this project**

When use SSO , for example in my case with traefik forward auth with Authentik (or any other sso), if we can't disable auth (https://github.com/seriousm4x/UpSnap/issues/60), It will be nice to add another mechanism of authentication.

**Describe the solution you'd like**

Add OIDC to UpSnap to be friendly authenticate with a SSO.

Thanks!

**Comment by seriousm4x** [comment]
Hi,
as far as i know this should already work. Head over to the backend at `localhost:8090/_/`, then:

* login
* `Settings` (wrench on the left)
* `Auth providers`
* Choose OpenID Connect

![grafik](https://github.com/seriousm4x/UpSnap/assets/23456686/636f0a03-0160-4f39-b3e7-3b523d39ef3d)

I've never used OIDC, so I hope this just works :)

**Comment by CygnusHyoga** [comment]
Thanks for the reply!! I will test it, and come back to post details :-)

**Comment by CygnusHyoga** [comment]
I made same tests. I can configure the OpenID Connect (oidc) in the admin panel and in the SSO, without a problem, but when I try to login in the login page of upsnap the oidc provider not appear.

In the the docs of pocketbase about oauth provider, we can make an ALL-IN-ONE integration:
https://pocketbase.io/docs/authentication#oauth2-integration

It's possible to add this in the source code? For example with a provider as a variable to support any provider of pocketbase:

...
const authData = await pb.collection('users').authWithOAuth2({ provider: '$customvariable' });
...

Maybe can pass the variable as environment variable in docker, so we can configure any provider we want?

Thanks again! I really like upsnap :-)

**Comment by seriousm4x** [comment]
The problem with OAuth2 is that anyone can just log in and get access. Anyone can log in with their Google account and have access to the dashboard. I wanted to avoid that, so only authorized users get access, therefore only user/password.

I can still create an environment variable for it, which will change the login form to OAuth2. You should only do this if you are aware of what I just wrote. In the home network this is completely safe, but other people might use this in their company.

**Comment by CygnusHyoga** [comment]
I agree with what you say and the security risks, I had not thought about it from that point of view.

Although perhaps it would be convenient to enable it only for OIDC, and not for ALLINONE? OIDC can be private, like any internal SSO (home or corporate).

...
const authData = await pb.collection('users').authWithOAuth2({ provider: 'oidc)' });
...

**Comment by seriousm4x** [comment]
I've added a button below the login form `Login with OIDC`. Pocketbase only allows OAuth for users, so OIDC is not available for admins. 
Make sure to have OIDC setup in http://localhost:8090/_/#/settings/auth-providers and it should work.

I've not tested this since I don't have an OIDC instance to test.
@CygnusHyoga let me know if it works for you with the latest beta [3.3.0-beta.2](https://github.com/seriousm4x/UpSnap/releases/tag/3.3.0-beta.2)

**Comment by CygnusHyoga** [comment]
I've tested the beta, I configure the SSO (authentik) and PocketBase OIDC provider with the correct SSO urls. I configure the ca-certs of the SSO inside the containers (private self signed authentik).

I can see the button, the button launch the authentication with de SSO/OIDC in a new windows, I can enter the credentials, I can authenticate with the SSO from upsnap, but after this steps, upsnap login page give this error:

{
  "errorDetails": "Failed create rule constraint: Only admins can create new accounts with OAuth2",
  "errorMessage": "Failed to authenticate."
}

Any ideas?

**Comment by seriousm4x** [comment]
I see what the problem is. Pocketbase has api rules to control permissions. The `create rule` is currently set to `admin only`  which only allows admins to create new users.

![image](https://github.com/seriousm4x/UpSnap/assets/23456686/aa10098b-18d6-402c-a427-b5816238fcef)

In your case a new user trys to signup on its own, which fails, because he is not allowed to.

Allowing everyone to create new users would result in the problem we had before. Everyone can signup and login. I've created [a discussion](https://github.com/pocketbase/pocketbase/discussions/2824) to see if its possible to deny signup via user/password but still allow signup via oauth2.

**Comment by seriousm4x** [comment]
Well, he instantly came up with a working solution. I've tried it with Twitch as a provider which worked for me, so OIDC should work as well.

Please try again with [3.3.0-beta.3](https://github.com/seriousm4x/UpSnap/releases/tag/3.3.0-beta.3)

**Comment by CygnusHyoga** [comment]
I've tested 3.3.0-beta.3 and OIDC works perfect!!!! Thanks!!!

**Comment by Ingener74** [comment]
Hi. How can i enable OIDC page? 

![Image](https://github.com/user-attachments/assets/98909e57-1467-4649-92b9-b6846efde790)

**Comment by seriousm4x** [comment]
> Hi. How can i enable OIDC page? UpSnap version: [4.6.1](https://github.com/seriousm4x/UpSnap/releases/tag/4.6.1)
> 
> ![Image](https://github.com/user-attachments/assets/98909e57-1467-4649-92b9-b6846efde790)

Check the [wiki](https://github.com/seriousm4x/UpSnap/wiki/Auth-providers).

**Comment by Ingener74** [comment]
@seriousm4x thanks))

**Comment by Ingener74** [comment]
@seriousm4x one more question. Is there any way to disable the form for local authentication and leave only authentication via OIDC/OAuth2?

**Comment by Ingener74** [comment]
@seriousm4x hi. Can you help me? Please

**Comment by seriousm4x** [comment]
> @seriousm4x hi. Can you help me? Please

You would need to modify the database configuration which might lead to future migration conflicts. It might cause future updates to fail. Therefore I don't recommend doing it unless absolutely necessary.

Go to the backend, users, edit collection, options and disable Identity/Password.

As I said, it's not officially supported and the login form will not reflect your change. It will still show the form, but the backend won't accept password attempts.

**Comment by Ingener74** [comment]
> > [@seriousm4x](https://github.com/seriousm4x) hi. Can you help me? Please
> 
> You would need to modify the database configuration which might lead to future migration conflicts. It might cause future updates to fail. Therefore I don't recommend doing it unless absolutely necessary.
> 
> Go to the backend, users, edit collection, options and disable Identity/Password.
> 
> As I said, it's not officially supported and the login form will not reflect your change. It will still show the form, but the backend won't accept password attempts.

Thanks :)
