### ISSUE TITLE
[REQUEST] Support for "Add All" during UI scan

### ISSUE THREAD

**Issue by gaby** [seriousm4x/UpSnap#104]
**The problem you currently have with this project**
Currently when running a wide scan through the UI, there's no way to add multiple devices. I tried scanning my local network with +20 devices, and I have to add them manually one by one.

**Describe the solution you'd like**
Add a button "Add all", that adds all the devices without "Unknown" to the list of devices.

**Comment by seriousm4x** [comment]
I've added this to [3.3.0-beta.2](https://github.com/seriousm4x/UpSnap/releases/tag/3.3.0-beta.2)

**Comment by gaby** [comment]
> I've added this to [3.3.0-beta.2](https://github.com/seriousm4x/UpSnap/releases/tag/3.3.0-beta.2)

Thank you!

**Comment by gaby** [comment]
@seriousm4x I just tried this again in a new instance and noticed that devices named "Unknown" get added to the home page. It's easy to replicate by scanning a whole /24 subnet. I can open a bug report if needed.

**Comment by seriousm4x** [comment]
I read your original issue again. I think I overread the part "without "Unknown" to the list of devices.". The "Add all" button currently adds all devices, whether Unknown or not. I can add a checkbox "Also add unknown devices", so you can decide for yourself if you want them or not.

**Comment by gaby** [comment]
> I read your original issue again. I think I overread the part "without "Unknown" to the list of devices.". The "Add all" button currently adds all devices, whether Unknown or not. I can add a checkbox "Also add unknown devices", so you can decide for yourself if you want them or not.

Yeah, that would be a good solution. Thanks!

**Comment by seriousm4x** [comment]
Will be available with the new tailwind frontend https://github.com/seriousm4x/UpSnap/commit/39dbecf7cb2f58427bb79432d3cd25ac17370057

**Comment by gaby** [comment]
> Will be available with the new tailwind frontend [39dbecf](https://github.com/seriousm4x/UpSnap/commit/39dbecf7cb2f58427bb79432d3cd25ac17370057)

Thank you! Looking forward!
