### ISSUE TITLE
[REQUEST] Support for DNS lookup during scan

### ISSUE THREAD

**Issue by gaby** [seriousm4x/UpSnap#105]
**The problem you currently have with this project**
After scanning a /24 with +20 devices they all show up with the same name on the UI. It would be very useful if we could specify one or many DNS servers to find the Name of each device using it's ipv4 address

**Describe the solution you'd like**
Add a flag or settings option to use a DNS server to convert  use the IPv4 address of the device to do a DNS lookup and use that Name when adding the device. This should only apply to devices that have both a ipv4/ipv6 address AND the name is not "Unknown"

**Comment by seriousm4x** [comment]
Good idea 👍🏼 

> This should only apply to devices that have both a ipv4/ipv6 address AND the name is not "Unknown"

Why that? My first thought was to make a DNS request when the device is Unknown.

**Comment by seriousm4x** [comment]
I've added this. When the device is "Unknown" it will perform a reverse dns lookup. I can't specify the dns server in go, so it will use the default system dns server. For docker containers the dns can be changed like this: https://github.com/seriousm4x/UpSnap/blob/master/docker-compose.yml#L16-L18

**Comment by gaby** [comment]
> Good idea 👍🏼
> 
> > This should only apply to devices that have both a ipv4/ipv6 address AND the name is not "Unknown"
> 
> Why that? My first thought was to make a DNS request when the device is Unknown.

When scanning something like /24, anything that doesnt have device shows as "Unknown" for me. While addresses that do have a device show up with the devics manufacturer name. 🤔

**Comment by seriousm4x** [comment]
So your table shows very IP address in the range?
What is the output of `nmap -sn -oX - 192.168.1.0/24 --host-timeout 500ms`? (replace your range)

**Comment by CygnusHyoga** [comment]
I can confirm what gaby comments:

- Device that doesnt have device shows as "Unknown" for me too.
- Addresses that do have a device show up with the devices manufacturer name.

Can we add the two columns? Hostname for DNS Hostname and MAC Vendor for MAC Vendor?

For example:

Hostname | IP |  MAC Address | MAC Vendor | Netmask

This will be more easy to identify devices from the their DNS lookups although the don't have a MAC Vendor.

I test how Angry IP Scanner show MAC Vendor for devices with no real device (virtual devices) and shows it as: [n/a]. I think this is ok, because they are non real devices?

**Comment by gaby** [comment]
> I can confirm what gaby comments:
> 
> * Device that doesnt have device shows as "Unknown" for me too.
> * Addresses that do have a device show up with the devices manufacturer name.
> 
> Can we add the two columns? Hostname for DNS Hostname and MAC Vendor for MAC Vendor?
> 
> For example:
> 
> Hostname | IP | MAC Address | MAC Vendor | Netmask
> 
> This will be more easy to identify devices from the their DNS lookups although those devices who do not have a MAC Vendor.
> 
> I test how Angry IP Scanner show MAC Vendor for devices with no real device (virtual devices) and shows it as: [n/a]. I think this is ok, because they are non real devices.

I like this idea, that's exactly the behavior i am seeing after doing a /24 scan

**Comment by seriousm4x** [comment]
> Can we add the two columns? Hostname for DNS Hostname and MAC Vendor for MAC Vendor?

Great idea. Here is how I choose the device name now:

1. DNS resolves? -> Pick the DNS name
2. DNS doesn't resolve? -> Fall back to mac vendor name
3. DNS doesn't resolve and no mac vendor name? -> don't add device to the table

This will also eliminate all "Unknown" device names. Mac vendor can still show as unknown, but thats not relevant.

![scan](https://github.com/seriousm4x/UpSnap/assets/23456686/2d336838-5489-4349-88f0-9b7085dc96c7)

**Comment by gaby** [comment]
> > Can we add the two columns? Hostname for DNS Hostname and MAC Vendor for MAC Vendor?
> 
> Great idea. Here is how I choose the device name now:
> 
> 1. DNS resolves? -> Pick the DNS name
> 2. DNS doesn't resolve? -> Fall back to mac vendor name
> 3. DNS doesn't resolve and no mac vendor name? -> don't add device to the table
> 
> This will also eliminate all "Unknown" device names. Mac vendor can still show as unknown, but thats not relevant.
> 
> ![scan](https://user-images.githubusercontent.com/23456686/250296043-2d336838-5489-4349-88f0-9b7085dc96c7.jpg)

Yeah that should cover all the use cases :-) I like it!

**Comment by CygnusHyoga** [comment]
Fantastic! :-)

**Comment by seriousm4x** [comment]
Beta build is done. Tell me if it's fixed :)
https://github.com/seriousm4x/UpSnap/releases/tag/3.3.0-beta.4

**Comment by CygnusHyoga** [comment]
It's work perfect! The only problem is visual one...the IP and MAC columns are too close together, maybe they need a little more space so they can be seen correctly.


![IPMAC](https://github.com/seriousm4x/UpSnap/assets/50732940/4e6ad798-f976-4a0a-abf3-63a22ddc4c48)
