### ISSUE TITLE
Node Sass does not yet support your current environment: Linux Unsupported architecture (arm64) with Node.js 12.x

### ISSUE THREAD

**Issue by Mizuho32** [seriousm4x/UpSnap#11]
## What happened
Hello. I'm trying to use UpSnap on aarch64 but as titled, it says
```
 [!] (plugin svelte) Error: Cannot find any of modules: sass,node-sass

Error: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm64) with Node.js 12.x
```

## Reproduce

1. Install `build-essential` in the container to avoid the error below but it's not the main topic.
   > npm ERR! gyp verb node dev dir /root/.cache/node-gyp/12.22.5
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/app/frontend/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /app/frontend/node_modules/which/which.js:57:18
2. After 1., the error appears.
    > app_1    | src/main.js → public/build/bundle.js...
app_1    | [!] (plugin svelte) Error: Cannot find any of modules: sass,node-sass
app_1    |
app_1    | Error: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm64) with Node.js 12.x
app_1    | For more information on which environments are supported please see:
app_1    | https://github.com/sass/node-sass/releases/tag/v7.0.1
app_1    | src/App.svelte
app_1    | Error: Cannot find any of modules: sass,node-sass
app_1    |
app_1    | Error: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm64) with Node.js 12.x
app_1    | For more information on which environments are supported please see:
app_1    | https://github.com/sass/node-sass/releases/tag/v7.0.1
app_1    |     at importAny (/app/frontend/node_modules/svelte-preprocess/dist/modules/utils.js:31:15)
app_1    |
app_1    | npm ERR! code 1
app_1    | npm ERR! path /app/frontend
app_1    | npm ERR! command failed
app_1    | npm ERR! command sh -c rollup -c
app_1    |
app_1    | npm ERR! A complete log of this run can be found in:
app_1    | npm ERR!     /root/.npm/_logs/2022-03-26T11_36_58_737Z-debug.log

I checked that the command `npm run build` outputs this error.
so, is arm64 really supported?

**Comment by R0GGER** [comment]
I have the same issue on a Raspberry Pi 4 (arm64).

**Comment by seriousm4x** [comment]
Sorry, I wasn't aware of this, since I don't use the arm64 version. I just made sure that the docker image builds successful. Also wasn't aware that nom packages could have problems on arm.

I'm on vacation right now, so I will take a look at this when I come back home. But for now, it's best for you to go back to v1 https://github.com/seriousm4x/UpSnap/tree/v1.4.1

**Comment by Mizuho32** [comment]
@seriousm4x I faced new problem #12

**Comment by seriousm4x** [comment]
I've replace node-sass with sass (which has arm64 support). It works on my pi4. Let me know if it works for you.

**Comment by Mizuho32** [comment]
It worked! Thank you
![image](https://user-images.githubusercontent.com/5453161/160516053-5a569162-cddd-4447-8cd7-bc3f67b8e93a.png)

For now, I'm working in bind volume (./app:/app) and modified it manually, docker image will be available?
and UpSnap outputs some errors that seem related to WebSocket. It's OK?

<details>
  <summary>Click to expand!</summary>

app_1    | src/main.js → public/build/bundle.js...
app_1    | created public/build/bundle.js in 1m 39.2s
app_1    |
app_1    | > svelte-app@1.0.0 start
app_1    | > sirv public --no-clear --host
app_1    |
app_1    |
app_1    |   Your application is ready~! 🚀
app_1    |
app_1    |   - Local:      http://0.0.0.0:7000
app_1    |   - Network:    http://192.168.1.32:7000
app_1    |
app_1    |  LOGS
app_1    |
app_1    |   [01:43:49] 200 ─ 33.79ms ─ /
app_1    |   [01:43:50] 200 ─ 2.39ms ─ /global.css
app_1    |   [01:43:50] 200 ─ 21.05ms ─ /build/bundle.js
app_1    |   [01:43:50] 200 ─ 24.70ms ─ /build/bootstrap.min.js
app_1    |   [01:43:50] 200 ─ 35.31ms ─ /build/bundle.css
app_1    |   [01:43:50] 200 ─ 7.50ms ─ /favicon.png
app_1    |   [01:43:50] 200 ─ 11.07ms ─ /build/webfonts/fa-solid-900.woff2
app_1    | [2022-03-29 01:43:50 +0000] [23] [INFO] ('192.168.1.37', 60868) - "WebSocket /wol/" [accepted]
app_1    | [2022-03-29 01:43:50 +0000] [23] [INFO] connection open
app_1    | [2022-03-29 01:43:50 +0000] [23] [ERROR] Exception in ASGI application
app_1    | Traceback (most recent call last):
app_1    |   File "/opt/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
app_1    |     return self.cursor.execute(sql, params)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute
app_1    |     return self.cursor.execute(query, args)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
app_1    |     res = self._query(query)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
app_1    |     db.query(q)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
app_1    |     _mysql.connection.query(self, query)
app_1    | MySQLdb._exceptions.ProgrammingError: (1146, "Table 'upsnap.wol_device' doesn't exist")
app_1    |
app_1    | The above exception was the direct cause of the following exception:
app_1    |
app_1    | Traceback (most recent call last):
app_1    |   File "/opt/venv/lib/python3.9/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 184, in run_asgi
app_1    |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
app_1    |     return await self.app(scope, receive, send)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/channels/routing.py", line 71, in __call__
app_1    |     return await application(scope, receive, send)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/channels/sessions.py", line 47, in __call__
app_1    |     return await self.inner(dict(scope, cookies=cookies), receive, send)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/channels/sessions.py", line 263, in __call__
app_1    |     return await self.inner(wrapper.scope, receive, wrapper.send)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/channels/auth.py", line 185, in __call__
app_1    |     return await super().__call__(scope, receive, send)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/channels/middleware.py", line 26, in __call__
app_1    |     return await self.inner(scope, receive, send)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/channels/routing.py", line 150, in __call__
app_1    |     return await application(
app_1    |   File "/opt/venv/lib/python3.9/site-packages/channels/consumer.py", line 94, in app
app_1    |     return await consumer(scope, receive, send)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/channels/consumer.py", line 58, in __call__
app_1    |     await await_many_dispatch(
app_1    |   File "/opt/venv/lib/python3.9/site-packages/channels/utils.py", line 51, in await_many_dispatch
app_1    |     await dispatch(result)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/channels/consumer.py", line 73, in dispatch
app_1    |     await handler(message)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/channels/generic/websocket.py", line 173, in websocket_connect
app_1    |     await self.connect()
app_1    |   File "/app/backend/wol/consumers.py", line 21, in connect
app_1    |     "devices": await self.get_all_devices(),
app_1    |   File "/opt/venv/lib/python3.9/site-packages/asgiref/sync.py", line 414, in __call__
app_1    |     ret = await asyncio.wait_for(future, timeout=None)
app_1    |   File "/usr/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
app_1    |     return await fut
app_1    |   File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
app_1    |     result = self.fn(*self.args, **self.kwargs)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/channels/db.py", line 13, in thread_handler
app_1    |     return super().thread_handler(loop, *args, **kwargs)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/asgiref/sync.py", line 455, in thread_handler
app_1    |     return func(*args, **kwargs)
app_1    |   File "/app/backend/wol/consumers.py", line 134, in get_all_devices
app_1    |     for dev in devices:
app_1    |   File "/opt/venv/lib/python3.9/site-packages/django/db/models/query.py", line 280, in __iter__
app_1    |     self._fetch_all()
app_1    |   File "/opt/venv/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
app_1    |     self._result_cache = list(self._iterable_class(self))
app_1    |   File "/opt/venv/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
app_1    |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
app_1    |     cursor.execute(sql, params)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
app_1    |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
app_1    |     return executor(sql, params, many, context)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
app_1    |     return self.cursor.execute(sql, params)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
app_1    |     raise dj_exc_value.with_traceback(traceback) from exc_value
app_1    |   File "/opt/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
app_1    |     return self.cursor.execute(sql, params)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute
app_1    |     return self.cursor.execute(query, args)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
app_1    |     res = self._query(query)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
app_1    |     db.query(q)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
app_1    |     _mysql.connection.query(self, query)
app_1    | django.db.utils.ProgrammingError: (1146, "Table 'upsnap.wol_device' doesn't exist")
app_1    | [2022-03-29 01:43:50 +0000] [23] [ERROR] closing handshake failed
app_1    | Traceback (most recent call last):
app_1    |   File "/opt/venv/lib/python3.9/site-packages/websockets/legacy/server.py", line 240, in handler
app_1    |     await self.close()
app_1    |   File "/opt/venv/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 779, in close
app_1    |     await asyncio.shield(self.close_connection_task)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1312, in close_connection
app_1    |     self.transport.write_eof()
app_1    |   File "uvloop/handles/stream.pyx", line 696, in uvloop.loop.UVStream.write_eof
app_1    |   File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
app_1    | RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x3ccb9020>; the handler is closed
app_1    | [2022-03-29 01:43:50 +0000] [23] [INFO] connection closed
app_1    |   [01:44:23] 200 ─ 3.49ms ─ /
app_1    |   [01:44:23] 200 ─ 14.83ms ─ /build/bundle.js
app_1    |   [01:44:23] 200 ─ 17.32ms ─ /build/bootstrap.min.js
app_1    |   [01:44:23] 200 ─ 21.02ms ─ /build/bundle.css
app_1    |   [01:44:24] 200 ─ 4.86ms ─ /favicon.png
app_1    | [2022-03-29 01:44:24 +0000] [20] [INFO] ('192.168.1.37', 60876) - "WebSocket /wol/" [accepted]
app_1    | [2022-03-29 01:44:24 +0000] [20] [INFO] connection open
app_1    | [2022-03-29 01:44:24 +0000] [20] [ERROR] Exception in ASGI application
app_1    | Traceback (most recent call last):
app_1    |   File "/opt/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
app_1    |     return self.cursor.execute(sql, params)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute
app_1    |     return self.cursor.execute(query, args)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
app_1    |     res = self._query(query)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
app_1    |     db.query(q)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
app_1    |     _mysql.connection.query(self, query)
app_1    | MySQLdb._exceptions.ProgrammingError: (1146, "Table 'upsnap.wol_device' doesn't exist")
app_1    |
app_1    | The above exception was the direct cause of the following exception:
app_1    |
app_1    | Traceback (most recent call last):
app_1    |   File "/opt/venv/lib/python3.9/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 184, in run_asgi
app_1    |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
app_1    |     return await self.app(scope, receive, send)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/channels/routing.py", line 71, in __call__
app_1    |     return await application(scope, receive, send)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/channels/sessions.py", line 47, in __call__
app_1    |     return await self.inner(dict(scope, cookies=cookies), receive, send)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/channels/sessions.py", line 263, in __call__
app_1    |     return await self.inner(wrapper.scope, receive, wrapper.send)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/channels/auth.py", line 185, in __call__
app_1    |     return await super().__call__(scope, receive, send)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/channels/middleware.py", line 26, in __call__
app_1    |     return await self.inner(scope, receive, send)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/channels/routing.py", line 150, in __call__
app_1    |     return await application(
app_1    |   File "/opt/venv/lib/python3.9/site-packages/channels/consumer.py", line 94, in app
app_1    |     return await consumer(scope, receive, send)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/channels/consumer.py", line 58, in __call__
app_1    |     await await_many_dispatch(
app_1    |   File "/opt/venv/lib/python3.9/site-packages/channels/utils.py", line 51, in await_many_dispatch
app_1    |     await dispatch(result)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/channels/consumer.py", line 73, in dispatch
app_1    |     await handler(message)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/channels/generic/websocket.py", line 173, in websocket_connect
app_1    |     await self.connect()
app_1    |   File "/app/backend/wol/consumers.py", line 21, in connect
app_1    |     "devices": await self.get_all_devices(),
app_1    |   File "/opt/venv/lib/python3.9/site-packages/asgiref/sync.py", line 414, in __call__
app_1    |     ret = await asyncio.wait_for(future, timeout=None)
app_1    |   File "/usr/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
app_1    |     return await fut
app_1    |   File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
app_1    |     result = self.fn(*self.args, **self.kwargs)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/channels/db.py", line 13, in thread_handler
app_1    |     return super().thread_handler(loop, *args, **kwargs)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/asgiref/sync.py", line 455, in thread_handler
app_1    |     return func(*args, **kwargs)
app_1    |   File "/app/backend/wol/consumers.py", line 134, in get_all_devices
app_1    |     for dev in devices:
app_1    |   File "/opt/venv/lib/python3.9/site-packages/django/db/models/query.py", line 280, in __iter__
app_1    |     self._fetch_all()
app_1    |   File "/opt/venv/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
app_1    |     self._result_cache = list(self._iterable_class(self))
app_1    |   File "/opt/venv/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
app_1    |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
app_1    |     cursor.execute(sql, params)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
app_1    |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
app_1    |     return executor(sql, params, many, context)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
app_1    |     return self.cursor.execute(sql, params)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
app_1    |     raise dj_exc_value.with_traceback(traceback) from exc_value
app_1    |   File "/opt/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
app_1    |     return self.cursor.execute(sql, params)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute
app_1    |     return self.cursor.execute(query, args)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
app_1    |     res = self._query(query)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
app_1    |     db.query(q)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
app_1    |     _mysql.connection.query(self, query)
app_1    | django.db.utils.ProgrammingError: (1146, "Table 'upsnap.wol_device' doesn't exist")
app_1    | [2022-03-29 01:44:24 +0000] [20] [ERROR] closing handshake failed
app_1    | Traceback (most recent call last):
app_1    |   File "/opt/venv/lib/python3.9/site-packages/websockets/legacy/server.py", line 240, in handler
app_1    |     await self.close()
app_1    |   File "/opt/venv/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 779, in close
app_1    |     await asyncio.shield(self.close_connection_task)
app_1    |   File "/opt/venv/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1312, in close_connection
app_1    |     self.transport.write_eof()
app_1    |   File "uvloop/handles/stream.pyx", line 696, in uvloop.loop.UVStream.write_eof
app_1    |   File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
app_1    | RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x3ccb85a0>; the handler is closed
app_1    | [2022-03-29 01:44:24 +0000] [20] [INFO] connection closed
  

</details>

**Comment by R0GGER** [comment]
Yup... it works now. I build a new docker image myself. 
Thanks!

**Comment by seriousm4x** [comment]
https://github.com/seriousm4x/UpSnap/releases/tag/v2.0.3
