### ISSUE TITLE
django.db.utils.ProgrammingError: (1146, "Table 'upsnap.wol_websocket' doesn't exist")

### ISSUE THREAD

**Issue by Mizuho32** [seriousm4x/UpSnap#12]
## What happened
From #11, I'm trying to run v1.4.1 on aarch64 but it says
> upsnap_django    | django.db.utils.ProgrammingError: (1146, "Table 'upsnap.wol_websocket' doesn't exist")

## Reproduce
Straightforward

## Check MySQL (mariadb) DB
Changed mysql to mariadb because no mysql image for arm64.
And I confirmed there does not exist the table 'upsnap.wol_websocket'.

> root@1d4c0b7296b2:/# mysql -u upsnap -p
> Enter password:
> Welcome to the MariaDB monitor.  Commands end with ; or g.
> Your MariaDB connection id is 8
> Server version: 10.4.8-MariaDB-1:10.4.8+maria~bionic mariadb.org binary distribution
>
> Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.
>
> Type 'help;' or 'h' for help. Type ' to clear the current input statement.
>
> MariaDB [(none)]> show databases;
> +--------------------+
> | Database           |
> +--------------------+
> | information_schema |
> | upsnap             |
> +--------------------+
> 2 rows in set (0.002 sec)
>
> MariaDB [(none)]> use upsnap;
> Database changed
> MariaDB [upsnap]> show tables;
> Empty set (0.001 sec)
>

**Comment by seriousm4x** [comment]
arm64 support is fixed in v2 now. so I`d suggest using v2 again.
