### ISSUE TITLE
[REQUEST] Link to devices

### ISSUE THREAD

**Issue by e-p-s** [seriousm4x/UpSnap#13]
Hi. Its possible to add a link to the devices?
For example i want to start a NAS. After its green, i want to go to NAS' Webgui, directly from UpSnap

**Comment by seriousm4x** [comment]
I could add that, but you have to think about what should be clickable and what the link is created from first.

Which part of the device should be clickable? The name or the ports? If the ports, you can simply link the ports. That would be no problem.

If the name should be clickable, how should the link be created? Should you be able to set the link in the settings, or should it be generated automatically from IP and port? If so, which port?

**Comment by e-p-s** [comment]
Perhaps we can make a new port, called "link". So everyone can define a custom port (80,8080,5000, etc) and open this, with a click.

**Comment by seriousm4x** [comment]
I've just added a field called link on a device card
