### ISSUE TITLE
[BUG] device stuck with yellow spinner

### ISSUE THREAD

**Issue by seriousm4x** [seriousm4x/UpSnap#135]
**Describe the bug**

It can happen that a device is stuck with a yellow spinner and the status does not change anymore. You have to either restart the container or change the status yourself in the backend.

I haven't found out yet when this happens. If someone has the same problem and knows a way to reproduce it reliably, please send a step by step guide.

**Comment by GauthierMenier** [comment]
Hello,
When I desactivate windows defender for both private and public networks, only status devices related to windows becomes green!

**Comment by seriousm4x** [comment]
Hi, thanks for suggesting. However, that is not the problem. The problem is when you wake a device that the status stays yellow forever and does not turn green or red again. Your instructions just allow pinging windows pcs.

**Comment by seriousm4x** [comment]
should be fixed with https://github.com/seriousm4x/UpSnap/commit/58d497eab1dc12b4176d991af9987cac4adce79c
