### ISSUE TITLE
Docker upsnap_app always restart

### ISSUE THREAD

**Issue by e-p-s** [seriousm4x/UpSnap#14]
coming from version 1.4

backuped the config an want to go to version 2.x

docker system prune -a
changed the the docker-compose.yml to latest

``
version: "3"
services:
  app:
    container_name: upsnap_app
    image: seriousm4x/upsnap:latest
    network_mode: host
    restart: unless-stopped
    environment:
      - FRONTEND_PORT=8000
      - BACKEND_PORT=8001
      - DB_TYPE=sqlite # required
      - REDIS_HOST=127.0.0.1 # required (make sure to use the same ip as below)
      - REDIS_PORT=6379 # required (make sure to use the same port as below)
      #- PING_INTERVAL=5 # optional (default: 5 seconds)
      #- DJANGO_SUPERUSER_USER=admin # optional (default: backend login disabled)
      #- DJANGO_SUPERUSER_PASSWORD=admin # optional (default: backend login disabled)
      #- DJANGO_SECRET_KEY=secret # optional (default: randomly generated)
      #- DJANGO_DEBUG=True # optional (default: False)
      #- DJANGO_LANGUAGE_CODE=de # optional (default: en)
      #- DJANGO_TIME_ZONE=Europe/Berlin # optional (default: UTC)
    depends_on:
      redis:
        condition: service_healthy
  redis:
    container_name: upsnap_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 10s

but the gui didt start:
https://pastebin.com/BtJZGq5m

**Comment by e-p-s** [comment]
Sadly the same:
https://pastebin.com/nC99uaNf

**Comment by seriousm4x** [comment]
Just had a look at it again. Are you sure you tried running v2?
In your first log it says
```
upsnap_app |   File "/app/django_wol/celery.py", line 14, in <module>
upsnap_app |     "schedule": int(os.getenv("PING_INTERVAL"))
```
This path is only used in v1. It doesn't exist in v2. Try pulling the latest image again.

**Comment by e-p-s** [comment]
shame to me. thx for your help.
