### ISSUE TITLE
WebSocket connection error when using lighttpd

### ISSUE THREAD

**Issue by Mizuho32** [seriousm4x/UpSnap#16]
I'm using Lighttpd and faced a WebSocket problem.

## What happened
When I map name to UpSnap (e.g. `upsnap.lan` to `localhost:7000 (frontend)`) by using lighttpd, WebScoket instantiation failed at `store.js:6`.

```js
const socket = new WebSocket(`ws://${location.hostname}:${BACKEND_PORT}/wol/`);
```

Because the WebSocket connection to host:port/wol/ (i.e. `upsnap.lan:7001/wol/`) is not possible due to the Lighttpd config to map name to UpSnap like below.

```
# This is for upsnap.lan access
$HTTP["host"] == "upsnap.lan" {
  proxy.balance = "hash"
  proxy.server  = ( "" => (
                            ( "host" => "127.0.0.1",
                              "port" => 7000 )
                          ) )
}

# This is for websocket connection
# https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_ModProxy#Example-websocket-proxy-to-noVNC-since-1446
$HTTP["url"] =~ "/wol" {
  proxy.server = ( "" => ( ( "host" => "127.0.0.1", "port" => "7001" ) ) )
  proxy.header = ( "upgrade" => "enable" )
}
```

So under this config, websocket access to `upsnap.lan:7001/wol/` is not possible because the first config (`# This is for upsnap.lan access`) prevents WebSocket connection to `upsnap.lan:7001/wol/`. Connection to `upsnap.lan/wol/` is OK actually.

## Current solution
I change the connection part as listed below but it is not good....
```js
let socket = new WebSocket(`ws://${location.hostname}:${BACKEND_PORT}/wol/`);
if (socket.readyState!=1){
    socket = new WebSocket(`ws://${location.hostname}/wol/`);
}
```

## What I want to ask
1. How do you avoid this problem in your environment? (Do Apache or nginx don't have this problem...?)
2. My understanding (`# This is for upsnap.lan access` prevents WebSocket connection) fundamentally wrong? There exists a better way to enable name mapping and WebSocket proxy for Lighttpd?

**Comment by seriousm4x** [comment]
I also have an instance running where I need a reverse proxy. I actually use the exxact same line as you do
```
const socket = new WebSocket(`ws://${location.hostname}/wol/`);
```
I havn't found a better way yet

**Comment by Mizuho32** [comment]
How about this https://github.com/Mizuho32/UpSnap/commit/451277b6ea6128a055923f69fcb87d1be0315ad5 with proxy config like,

```
# For name resolv
$HTTP["host"] == "upsnap2.lan" {
...
}

# For WebSocket
$SERVER["socket"] == ":8002" {
  $HTTP["host"] == "upsnap2.lan" {
    $HTTP["url"] =~ "^/wol" {
      proxy.server = ( "" => ( ( "host" => "localhost", "port" => "8001" ) ) )
      proxy.header = ( "upgrade" => "enable" )
    }
  }
}
```

**Comment by seriousm4x** [comment]
I don't think I quite understand. What is [WS_PROXY_PORT](https://github.com/Mizuho32/UpSnap/commit/451277b6ea6128a055923f69fcb87d1be0315ad5#diff-278411d1fa838b847d5bb5f800dfd01ad8ad82202e06cbeb7c0cea2afcfc4381R54) meant to be? Isn't it just BACKEND_PORT with a different name?

And where are you running lighttpd in your example? Inside the container or outside of docker?

A full example (maybe even a working pull request) would be very helpful :)

**Comment by Mizuho32** [comment]
1. "Isn't it just BACKEND_PORT with a different name?"
Yes, for development but No for production (behind proxy)
2.  "Inside the container or outside of docker?"
In my case, outside of docker.
3. Of course I'll send a PR. I just wanted to confirm your opinion.

The detail follows below.

## Detail
### Assumption
1. upsnap fronend listen on `8000`
2. backend (WebSocket) listen on `8001`
3. proxy has a config that maps the name `upsnap.com` to `localhost:8000`
4. Proxy and upsnap are running on the same machine.

### How works
Under this rule, the access to `ws://upsnap.com:8001/wol/` failed because the proxy works and maps `upsnap.com` to `localhost:8000` (it's ok when development. accessing to `localhost:8001/wol/` is no problem)

Adding proxy config that maps `upsnap.com:8001` to `localhost:8001` doesn't work either because `8001` is already used.
So I use `8002` port (`WS_PROXY_PORT`) to receive WebSocket connection and route it to `localhost:8001`.

We can omit `WS_PROXY_PORT` when the development or upsnap is running on other machines.


My idea is this↑. Is that OK? How about your opinion?

**Comment by seriousm4x** [comment]
Ah ok I understand now. Sounds good to me. I like the idea.
I'd be nice if everything proxy related is handled within the container. But I think it's not possible due to host networking :/
When the proxy needs to run on the host, we should include come config examples for common webservers like nginx and caddy, because people will use different webservers.

**Comment by Mizuho32** [comment]
Thank you for your review.
I'll send a PR and, yes, some config example for major webservers is good but I only have a Lighttpd environment...
Could you try it for your webservers if you use Nginx?

**Comment by tristan-k** [comment]
I'm using [nginx proxy manager](https://nginxproxymanager.com/) but I'm having a hard time to incoperate the necessary changes in order for UpSnap to work.

**Comment by gstrauss** [comment]
I do not quite understand exactly what you are trying to do here, but lighttpd supports a number of configuration options which are not being used here, e.g.
```
# This is for websocket connection
# https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_ModProxy#Example-websocket-proxy-to-noVNC-since-1446
proxy.server = ( "/wol" => ( ( "host" => "127.0.0.1", "port" => "7001" ) ) )
proxy.header = ( "upgrade" => "enable" )

# This is for upsnap.lan access
$HTTP["host"] == "upsnap.lan" {
  proxy.balance = "hash"
  proxy.server  = (
        "/wol" => ( ( "host" => "127.0.0.1",  "port" => 7001 ) ),
        ""     => ( ( "host" => "127.0.0.1",  "port" => 7000 ) ) )
}
```

**Comment by jarrettgilliam** [comment]
I'm running into the same issue using nginx. I can submit code or reverse proxy examples. Is there a PR for this yet?

**Comment by seriousm4x** [comment]
> I'm running into the same issue using nginx. I can submit code or reverse proxy examples. Is there a PR for this yet?

No, not yet

**Comment by jarrettgilliam** [comment]
OK, a variation of the changes discussed here are in pull request #22 for review.

**Comment by seriousm4x** [comment]
#22 got merged
