### ISSUE TITLE
[BUG] Portrait Mobile view slightly overlaps with longer title

### ISSUE THREAD

**Issue by beastarman74** [seriousm4x/UpSnap#168]
**Describe the bug**
When viewing the site on my mobile in portrait mode the title overlaps the menu items.

This is not evident in landscape mode. 

This appears to be completely cosmetic and does not impact the use of the app. 

**To Reproduce**
Access site on mobile in portrait orientation. With title of the app longer than 9 characters in length. 

**Expected behavior**
Mobile view does not have display issue. 

**Logs**
n/a

**Screenshots**
Firefox Nightly:
 ![Screenshot_20230816_171428](https://github.com/seriousm4x/UpSnap/assets/44511355/e863ac67-bc28-44e8-8e84-f569a365beac)

Chrome Dev and Chrome Browsers:
![Screenshot_20230816_172421](https://github.com/seriousm4x/UpSnap/assets/44511355/252961de-c93e-4819-b47d-5de6cfd53807)

Kiwi Browser 
![Screenshot_20230816_172308](https://github.com/seriousm4x/UpSnap/assets/44511355/b9b93024-e74c-49af-b8bf-b5f7e4bf3e8e)

**Host OS (and version)**
Raspberry Pi OS / Debian Bookworm 64bit

**Host Architecture**
arm64 (Raspberry Pi 4) 

**Brower (if relevant)**
Firefox Nightly v118.0a1
Chrome: 115.0.5790.166 
Chrome Dev: 117.0.5938.0
Kiwi Browser: 116.0.5845.70 

**Additional context**
n/a

**Comment by seriousm4x** [comment]
Ah thanks. As I don't use the website title normally, I ididn't notice this.
I will just hide it (maybe put it in the overflow menu) in the next release
