### ISSUE TITLE
[REQUEST] Support for overriding fields during Add All

### ISSUE THREAD

**Issue by gaby** [seriousm4x/UpSnap#169]
**The problem you currently have with this project**

First of all congrats on the V4 release, the new UI looks amazing. The UX experience is also miles ahead of V3. 

Lets say for example that you have a /16 network (10.8.0.0/16), which is divided into /24's based on purpose.

I would like to add each /24 into a separate group, and that works right now. The problem is that to do that I have to scan each /24 individually and UpSnap auto-calculating the netmask based on the IP provided. Because these devices live in a /16 when they get auto-assigned a /24 netmask the WoL stops working unless I manually edit the device and change it to /16.

**Describe the solution you'd like**

When using the "Add All" option in the Scan Page, there should be an option to override fields that UpSnap is auto-calculating (ex. netmask).

**Comment by seriousm4x** [comment]
So basically just an input form which changes the subnet mask for all devices?

**Comment by gaby** [comment]
@seriousm4x Yes that should work. I think that's the only field auto-generated?

**Comment by gaby** [comment]
Thanks! 💪
