### ISSUE TITLE
After editing the properties of any device, the dialog box doesn't fade away, nor does it notify that changes have been saved

### ISSUE THREAD

**Issue by drtech981** [seriousm4x/UpSnap#18]
If you bring up the device properties of any device, make changes to it (ports/commands) and click on save changes, there's **no notification** to tell if the changes have been synced nor does the box fade away automatically.

Either would be fine, but better would be that between 'Delete' and 'Save Changes', gets displayed something 'Changes Saved'/'Changes Synced', so that you don't have to bring up the properties tab again and again.

Thanks for the efforts !

**Same goes for when adding a device manually, we need some kind of visual prompt.**

**Comment by seriousm4x** [comment]
Sorry for responding late - was busy.
I've added a notification if the save was successful or if an error happened. This also applies to any kind of device changes (also adding devices or importing json backup).
