### ISSUE TITLE
After clicking on the power toggle, the button goes into an infinite loop

### ISSUE THREAD

**Issue by drtech981** [seriousm4x/UpSnap#19]
After you click on the power toggle button, it becomes unclickable and goes into an infinite loop until the device can/cannot be pinged (wake-up or shutdown respectively). Becomes hard to reissue a wake-up command unless the page is refreshed.

The button should not change into a loop, instead the button should change according to the next sent ping (the ping that happens regularly every 5 seconds).

**Comment by drtech981** [comment]
Please push changes to the docker images as well.

**Comment by seriousm4x** [comment]
I have some more small changes to do and then I will push a new image
