### ISSUE TITLE
[BUG] Docker - WOL fails to wake target machine

### ISSUE THREAD

**Issue by Corban-Lee** [seriousm4x/UpSnap#194]
UpSnap fails to wake my primary Linux machine. I am able to wake the primary machine directly on the server using the `wakeonlan` command, and I am also able to ping my primary device from the container console for UpSnap, although the wake feature does not work from the webgui, despite being able to track when the target is online/offline.

**To Reproduce**
1. Go to the web interface
2. Add target device
3. Attempt to WOL using the web interface for the target

**Expected behavior**
The target machine wakes

**Logs**
```
[INFO] 2023/09/04 20:55:13 pb.go:228: Ping interval set to @every 3s

2023/09/04 20:55:13 Server started at http://0.0.0.0:8090

├─ REST API: http://0.0.0.0:8090/api/

└─ Admin UI: http://0.0.0.0:8090/_/
```

**Screenshots**

**Host OS (and version)**
Ubuntu Server 22.04.3 LTS

**Host Architecture**
amd64

**Additional context**
Docker version 24.0.5
All other means of waking the target work (not using upsnap).
I can ping the target from the UpSnap container

**Comment by seriousm4x** [comment]
> I am able to wake the primary machine directly on the server using the wakeonlan command

You mean outside the container, on the host, right?

1. Could you post your docker config? Are you using [host network](https://github.com/seriousm4x/UpSnap/blob/master/docker-compose.yml#L6) for the container?
2. Could you try to run `awake` from inside the container?
```sh
docker exec -it UpSnap sh
apk update
apk add awake
awake <YOUR_MAC>
```
If that doesn't work as well, it's probably not related to UpSnap but rather the container setup.

**Comment by stolp** [comment]
I was falling into the same trap yesterday when mindlessly configuring bridge networking.

Maybe this can be made more prominent on the start page/documentation?

**Comment by seriousm4x** [comment]
> I was falling into the same trap yesterday when mindlessly configuring bridge networking.

Let's see if that's actually what happened here.

> Maybe this can be made more prominent on the start page/documentation?

When I find the time, I will add a troubleshooting section to the wiki.
