### ISSUE TITLE
[REQUEST] Can wake on lan for a windows machine?

### ISSUE THREAD

**Issue by moonstarsky37** [seriousm4x/UpSnap#203]
**The problem you currently have with this project**
UpSnap cannot wake windows machine but command in linux like wakeonlan can do.

**Describe the solution you'd like**
This is a great project for me as it offers a lightweight and user-friendly way to control machines. After conducting some tests(binary file and docker), I found that I couldn't wake up Windows machines, although the native Linux command "wakeonlan" worked perfectly. Later, upon inspecting the imported package, it seems that it doesn't support waking up Windows machines (I tested it on two Windows 11 machines). You can check out the package at https://github.com/mdlayher/wol.
Because this is not actually a bug in the development documentation process, I inquired about this issue as a feature request. Thank you for creating this repository.

**Comment by seriousm4x** [comment]
Wake on lan has nothing to do with the installed operating system. Yes, you can change power settings or NIC settings in Windows, but the BIOS/UEFI takes care of the wake event, not the operating system.

Also, I use it with various windows machines. From windows 10 to windows 11 and they all wake as expected. So claiming that

> it doesn't support waking up Windows machines

is not true. The issue is somewhere else.

* What docker config did you use? Make sure to use `network_mode: host` like [here](https://github.com/seriousm4x/UpSnap/blob/master/docker-compose.yml#L6).
* When you ran the `wakeonlan` command, did you run it on the same host as the upsnap binary? Did you use any VM or container?
* Was the upsnap binary executed as admin/root?

**Comment by moonstarsky37** [comment]
Thank you for your response. Before responding, let me briefly explain what I am currently testing in the hope of providing sufficient information.

In the first test, I was running Windows 11. I downloaded the release binary file and executed it with administrator privileges using the following command in CMD:

```
.\Downloads\upsnap.exe serve --http=0.0.0.0:8090
```

This allowed me to successfully wake up Linux machines on the local network, but it did not work for another Windows 11 machine. In addition, when the machine was off, it displayed a red status in the interface. Clicking it directly also resulted in an error message: `[ERROR] 2023/09/07 14:24:40 handlers.go:30: win11_2%!(EXTRA string=not online after 2 min)`.

The second test involved using Linux to perform Wake-on-LAN (WOL) on this machine, with similar settings:

```
sudo chmod +x upsnap
./upsnap serve --http=0.0.0.0:8090
```

However, it still failed to start or correctly detect the power status.

The third test involved using the following `docker-compose.yml` configuration:

```
version: "3"
services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:4
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data:/app/pb_data
```

Then I executed `docker compose up`, but the result was similar to the second test.

Here are the answers to your questions:

* Was the upsnap binary executed as admin/root?
  - Yes, it was executed as admin/root in all three tests.

* What docker config did you use? Make sure to use network_mode: host like here.
  - I used the docker configuration as shown in the third test, with `network_mode: host`.

* When you ran the wakeonlan command, did you run it on the same host as the upsnap binary?
  - Yes, I ran the wakeonlan command on the same host as the upsnap binary. I also tried using an application like https://www.depicus.com/wake-on-lan/wake-on-lan-monitor to check if it could receive the magic packets correctly. Packets sent via Linux commands were received correctly, but packets sent via UpSnap by clicking the button were not received.

* Did you use any VM or container?
  - I did not use a VM. I tested waking up physical machines in all my tests.

**Comment by seriousm4x** [comment]
You setup looks fine.
I can only think of the mac adress being wrong, but aside from that, I'm rather clueless.

If you can come up with a list (as short as possible) so I can reproduce the error would be very helpful. From your description so far, it works fine for me :/

**Comment by moonstarsky37** [comment]
Actually, I'm not quite sure about the meaning of "netmask being wrong" you mentioned. To be more precise, as far as I know, Wake-on-LAN (WoL) operates at the second layer of the OSI model, and the concept of netmask is associated with the third layer. In theory, if WoL is being used within the same local area network, there should be no need to configure a netmask.

When I use Ubuntu commands for WoL, I don't need to specify a netmask; simply providing the MAC address is sufficient to successfully wake up a device. However, in UpSnap, I did configure it as 255.255.255.0 (although I'm not entirely sure why this setting is required).

As for your mention of a "list," I'm not entirely sure what list you are referring to, but if it's something you'd like me to provide if convenient, I will do my best to assist.

**Comment by seriousm4x** [comment]
The netmask is used to calculate the broadcast address. Wikipedia has a whole lot more info on that https://en.wikipedia.org/wiki/Wake-on-LAN

> Because Wake-on-LAN is built upon broadcast messaging, it can generally only be used within a [subnet](https://en.wikipedia.org/wiki/Subnet). Wake-on-LAN can, however, operate across any network in practice, given appropriate configuration and hardware, including remote wake-up across the Internet.

> The magic packet is sent on the [data link layer](https://en.wikipedia.org/wiki/Data_link_layer) (layer 2 in the [OSI model](https://en.wikipedia.org/wiki/OSI_model)) and when sent, is broadcast to all attached devices on a given network, using the network [broadcast address](https://en.wikipedia.org/wiki/Broadcast_address);

Ubuntus wakeonlan command uses 255.255.255.255 as default broadcast address, that's why you dont need to enter anything. See `-i` option for [wakeonlan](https://manpages.ubuntu.com/manpages/xenial/man1/wakeonlan.1.html).

---

> I did configure it as 255.255.255.0

This is correct when you use a /24 subnet, eg. 192.168.1.0/24. If you use something different, you can use `ipcalc`:
```
~ ❯❯❯ ipcalc 192.168.1.56/24
Address:   192.168.1.56         11000000.10101000.00000001. 00111000
Netmask:   255.255.255.0 = 24   11111111.11111111.11111111. 00000000
Wildcard:  0.0.0.255            00000000.00000000.00000000. 11111111
=>
Network:   192.168.1.0/24       11000000.10101000.00000001. 00000000
HostMin:   192.168.1.1          11000000.10101000.00000001. 00000001
HostMax:   192.168.1.254        11000000.10101000.00000001. 11111110
Broadcast: 192.168.1.255        11000000.10101000.00000001. 11111111
Hosts/Net: 254                   Class C, Private Internet
```

---

> As for your mention of a "list," I'm not entirely sure what list you are referring to

I just mean a simple step by step "guide" how I can reproduce this. If possible, make sure that the problem occurs in other networks as well.

**Comment by moonstarsky37** [comment]
Thank you for your response. Following your advice, I changed the netmask of the Windows machine to 255.255.255.255. Now, I have successfully tested receiving the wake-up packets using Wake-on-LAN Monitor. After manually shutting down the machine, I was also able to wake it up correctly using UpSnap. I appreciate your help in identifying the blind spot I had overlooked.

However, although I can successfully send packets to wake up the machine, the status displayed in UpSnap is consistently red, indicating the machine is off.(although it is power on) I'm not quite sure about the factors causing this, but being able to wake up the machine correctly has resolved my primary issue.

**Comment by seriousm4x** [comment]
Good to hear. Windows firewall blocks ping requests by default. You have to allow `File and Printer Sharing (Echo Request - ICMPv4-In)` in windows firewall.
https://kb.iu.edu/d/aopy

**Comment by moonstarsky37** [comment]
I'm sorry for the late response. Thank you for your reply. After some research, I now understand its purpose. Although I didn't find this specific item in the firewall settings directly, I was able to resolve it using the following command in powershell:

```
netsh advfirewall firewall add rule name="ICMP Allow incoming V4 echo request" protocol="icmpv4:8,any" dir=in action=allow
```

I can now successfully determine the computer's power status. I appreciate your patient and attentive responses. I believe I can close this issue now. Thank you for clarifying and resolving the problem.
