### ISSUE TITLE
Can UpSnap be used using portainer on RPi 4?

### ISSUE THREAD

**Issue by JulesHageman** [seriousm4x/UpSnap#21]
Hi seriousm4x,

You made a great tool, really enjoy using it for the last couple of days and wanted to install it on a Raspberry Pi 4 using Portainer.
So this is not an issue so much, more a question of the usability of this docker container using Portainer.
When I create this in Portainer using the docker-compose-sqlite.yml as a template, when I navigate to the IP-address of the RPi using the port 8000, I get the message "Not Found. The requested resource was not found on this server.".

Config is like this, there is also a Redist container on the same RPi configured with port 6379 (host) to 6379 (container).
![image](https://user-images.githubusercontent.com/75277263/174480716-7d5e1862-493d-4272-a9c3-6c48c1793bb4.png)

Would you be able to shed any light how to make this great image working using Portainer?
Thanks for the time investment creating and publishing this great tool.

**Comment by seriousm4x** [comment]
I think the problem is your you mapped port 8000 to port 8001.
Actually it should be 8000 to 8000 and 8001 to 8001. So 2 port configs are required.

**Comment by JulesHageman** [comment]
You sir are great! That was it, thanks!
I thought it has to be 8000:8001 because of the following in your supplied example docker compose file
      - FRONTEND_PORT=8000
      - BACKEND_PORT=8001
But I guess that is just me lacking experience using Docker at this moment still.
I'm able to get to the web interface and UpSnap is able to use Redist for pinging devices (which can show up/down), only not able to successfully send magic packets as of yet, so that I need to get fixed.

If you might have any idea what this is causing that would be great, otherwise I will try and post if I get it resolved.

**Comment by seriousm4x** [comment]
Probably because [host networking](https://github.com/seriousm4x/UpSnap/blob/master/docker-compose-sqlite.yml#L6)

**Comment by JulesHageman** [comment]
@seriousm4x  thank u so much for all the support, that was it.
So in summary, if anyone else is experiencing the same issue when using Portainer with little experience using Docker..

**Create volumes for containers**
- Create 2 new volumes using the default configuration; one for Redist, one for UpSnap, choose your own name.

**Create UpSnap container**
- Create container using 'seriousm4x/upsnap:latest' or 'seriousm4x/upsnap' (same outcome)
- Mount /config to UpSnap volume
- Bind port 8000:8000 and 8001:8001
- Use network mode Host
- Set restart policy to Always
- Configure following environment variables for this UpSnap container
FRONTEND_PORT = 8000
BACKEND_PORT = 8001
DB_TYPE = sqlite
REDIS_HOST = <host IP of Redis container> if running on same Docker host, use same IP (or maybe localhost?)
REDIS_PORT = 6379

**Create Redis container**
- Create using 'redis:alpine'
- Mount /config to Redis volume
- Bind port 6379:6379
- Use network mode Host
- Set restart policy to Always
- No custom environment variables needed to configure

**Comment by DaHyper** [comment]
I'm trying to get this working on Portainer as well and the website won't load at all. Is there anything else that I need to add so it works?

**Comment by DaHyper** [comment]
I'm trying to get this working on Portainer as well and the website won't load at all. Is there anything else that I need to add so it works?
![Screenshot 2022-08-04 010145](https://user-images.githubusercontent.com/60417296/182766881-9705d691-e8e7-4121-a9ff-9001e4a8ca83.png)

---
Extra things that could possibly help figure out my issue:
![extra](https://user-images.githubusercontent.com/60417296/182767469-e436b1ea-ea5d-479b-8bb4-5daf59358f5b.png)

**Comment by DaHyper** [comment]
I'm trying to get this working on Portainer as well and the website won't load at all. Is there anything else that I need to add so it works?
![Screenshot 2022-08-04 010145](https://user-images.githubusercontent.com/60417296/182766881-9705d691-e8e7-4121-a9ff-9001e4a8ca83.png)

---
**Extra things that could possibly help figure out my issue:**
![extra](https://user-images.githubusercontent.com/60417296/182767469-e436b1ea-ea5d-479b-8bb4-5daf59358f5b.png)

**Comment by DaHyper** [comment]
I'm trying to get this working on Portainer as well and the website won't load at all. Is there anything else that I need to add so it works?
![Screenshot 2022-08-04 010145](https://user-images.githubusercontent.com/60417296/182766881-9705d691-e8e7-4121-a9ff-9001e4a8ca83.png)

---
**Extra things that could possibly help figure out my issue:**
![extra](https://user-images.githubusercontent.com/60417296/182767469-e436b1ea-ea5d-479b-8bb4-5daf59358f5b.png)
---
_When I set the ports as 2 separate ones they combine into this weird one:_
![beforeafter](https://user-images.githubusercontent.com/60417296/182771007-0c074b58-f5cc-48f4-964d-705ecc679d0f.png)

**Comment by seriousm4x** [comment]
Have you checked the logs?

**Comment by DaHyper** [comment]
This is what I see in the logs: [https://pastebin.com/tKU5wScW](https://pastebin.com/tKU5wScW)

**Comment by DaHyper** [comment]
This is what I see in the logs: [https://pastebin.com/tKU5wScW](https://pastebin.com/tKU5wScW)
Do I need to install something else for **django**? Because that has a bunch of stuff in there.

**Comment by seriousm4x** [comment]
I think you are missing the
```
    volumes:
      - ./db/:/app/backend/db/
```
from the [docker-compose file](https://github.com/seriousm4x/UpSnap/blob/master/docker-compose-sqlite.yml#L22-L23)

**Comment by DaHyper** [comment]
**volumes:
      - ./db/:/app/backend/db/**
Is in my docker compose file now, but there is no website when I go to the port.

**Comment by DaHyper** [comment]
@JulesHageman If you still have UpSnap on Portainer, could you send a screenshot of the ports menu?
