### ISSUE TITLE
[REQUEST] Individual Broadcast address to wakeup devices in other Subnets

### ISSUE THREAD

**Issue by MrSliff** [seriousm4x/UpSnap#225]
**The problem you currently have with this project**
WOL in another Subnet is not possible, because for this it is needed to send the WOL packet to the broadcast address of the specific subnet. I.e. wake up device in 192.168.2.0/24 subnet from 192.168.1.0/ subnet, you need to send a packet to 192.168.2.255

**Describe the solution you'd like**
Add a field for a broadcast address to redirect WOL packets to the subnet the devices sits in. 

For example: [Broadcast address: 192.168.2.255], scan the IP-Adrress and Subnet field to set the default value based on the ip address for device monitoring.

**Comment by seriousm4x** [comment]
This should already work if you have a proper router setup in your network. Read more here https://serverfault.com/questions/285166/wake-on-lan-over-different-subnets

The broadcast address is [automatically calculated](https://github.com/seriousm4x/UpSnap/blob/master/backend/networking/magicpacket.go#L54-L80) by the ip and netmask. There should be no need for an extra broadcast address field.

In your example the netmask should be 255.255.255.0 and upsnap will use 192.168.2.255 already.
