### ISSUE TITLE
No persistent volumes for sqlite version ?

### ISSUE THREAD

**Issue by drtech981** [seriousm4x/UpSnap#23]
Config is lost when rebuilding the stack using sqlite, maybe since no persistent volumes are used ?

**Comment by seriousm4x** [comment]
Was possible before, but now its easier. Just add volumes with the [path to your compose](https://github.com/seriousm4x/UpSnap/blob/master/docker-compose-sqlite.yml#L22-L23
).
Make sure to use v2.2.2 once [the image is builded](https://github.com/seriousm4x/UpSnap/actions/runs/2769123089).
