### ISSUE TITLE
[REQUEST] Some devices don't wake up to the first magic packet sent

### ISSUE THREAD

**Issue by diepeterpan** [seriousm4x/UpSnap#239]
First of all, thank you for the work towards this.

**The problem you currently have with this project**
Currently, some devices don't wake up to the first magic packet sent and need a second or third one in quick succession, seems like only one packet is currently sent and then I have to wait 2 minutes before I can attempt again.  Which turns out futile as the time elapsed it is a waste and not fast enough in succession.

**Describe the solution you'd like**
Can there be maybe two changes per device created:
1) A checkbox to select sending multiple magic packets in succession (e.g. send _n_ magic packets, e.g. enter a number)
2) Option to override the 2 minutes to a custom interval with a minimum of 0 **seconds**; minutes is too long

**Additional context**
None

**Comment by seriousm4x** [comment]
Sending multiple packets (spamming) doesn't sound like a reliable solution to me. It's like treating the symptoms but not the source. Magic packets are sent via UDP, so maybe there is packet loss on your network?

I agree with you though on a customizable cool down. If set to 0 seconds you could spam magic packets yourself if that's really the only option.

**Comment by diepeterpan** [comment]
> Sending multiple packets (spamming) doesn't sound like a reliable solution to me. It's like treating the symptoms but not the source. Magic packets are sent via UDP, so maybe there is packet loss on your network?
> 

UDP by nature is unreliable and for that reason, it might make sense to build in some re-send by means of multiple packets with some form of delay.

> I agree with you though on a customizable cool down. If set to 0 seconds you could spam magic packets yourself if that's really the only option.

It would only cause spam if the code automatically repeat the action, at least with 0 seconds the user will have to option to send multiple packets by means of multiple presses on the defined machine icon. Which might solve requirement 1.

If I am the only one experiencing this problem then by all means I apologize, I will try and hunt the packet going stray.

**Comment by diepeterpan** [comment]
> > Sending multiple packets (spamming) doesn't sound like a reliable solution to me. It's like treating the symptoms but not the source. Magic packets are sent via UDP, so maybe there is packet loss on your network?
> 
> UDP by nature is unreliable and for that reason, it might make sense to build in some re-send by means of multiple packets with some form of delay.
> 
> > I agree with you though on a customizable cool down. If set to 0 seconds you could spam magic packets yourself if that's really the only option.
> 
> It would only cause spam if the code automatically repeat the action, at least with 0 seconds the user will have to option to send multiple packets by means of multiple presses on the defined machine icon. Which might solve requirement 1.
> 
> If I am the only one experiencing this problem then by all means I apologize, I will try and hunt the packet going stray.

Hmmmm, I am finding UDP packet loss, I am troubleshooting.......

**Comment by seriousm4x** [comment]
> If I am the only one experiencing this problem then by all means I apologize, I will try and hunt the packet going stray.

So far, you're the only one I've heard of with this problem. If others have the problem, I would change something. I might add a "Force wake" option to the "more" dropdown menu which will send like 10 (?) packets to compensate for package loss.

> Hmmmm, I am finding UDP packet loss, I am troubleshooting....... Seems to be a problem with WOL packets over OpenWRT WDS network :-(.

If you find a solution, please let us know here :)

**Comment by diepeterpan** [comment]
> If you find a solution, please let us know here :)

Good and bad news, the WOL packet's are not getting lost via OpenWRT WDS.  So it must be either the BIOS or Windows NIC configuration, it just stops working/waking after a day or two.  Well, I will dig in.  Just that 2 minute waiting time, if it can be customizable per device would be handy.  BTW, during the countdown, one can edit the config, e.g. change netmask and when the countdown ends it reverts to the value before the edit.

![image](https://github.com/seriousm4x/UpSnap/assets/15066052/b3c8aa0f-755c-4086-a054-0646ca73897e)

**Comment by diepeterpan** [comment]
> > If you find a solution, please let us know here :)
> 
> Good and bad news, the WOL packet's are not getting lost via OpenWRT WDS. So it must be either the BIOS or Windows NIC configuration, it just stops working/waking after a day or two. Well, I will dig in. Just that 2 minute waiting time, if it can be customizable per device would be handy. BTW, during the countdown, one can edit the config, e.g. change netmask and when the countdown ends it reverts to the value before the edit.
> 
> ![image](https://user-images.githubusercontent.com/15066052/271080704-b3c8aa0f-755c-4086-a054-0646ca73897e.png)

I configured the BIOS and now it wake-up on the first packet.  It is an ASUS MB so I followed this -[ ](https://www.anyviewer.com/how-to/asus-bios-wake-on-lan-2578.html)

**Comment by pietje666** [comment]
> > If I am the only one experiencing this problem then by all means I apologize, I will try and hunt the packet going stray.
> 
> So far, you're the only one I've heard of with this problem. If others have the problem, I would change something. I might add a "Force wake" option to the "more" dropdown menu which will send like 10 (?) packets to compensate for package loss.
> 
> > Hmmmm, I am finding UDP packet loss, I am troubleshooting....... Seems to be a problem with WOL packets over OpenWRT WDS network :-(.
> 
> If you find a solution, please let us know here :)

Got the same issue, also Asus motherboard though. Sometimes it works sometimes it doesnt work and when i try it again after the time it suddenly does work. 

What is the reason i am not allowed to spam it a few times?
