### ISSUE TITLE
Shutdown commands

### ISSUE THREAD

**Issue by bpmarine** [seriousm4x/UpSnap#24]
Great project, congratulations.

Would it be possible to enable other shell commands via the shutdown section?. As mentioned here https://www.reddit.com/r/selfhosted/comments/pz3u9u/comment/ijqaeb1/?utm_source=share&utm_medium=web2x&context=3, I managed to get sshpass working, but this requires username and password in plain text and I haven't found a way to get UpSnap to read a password from a file. 

All I really want to do is send a curl request from this command section, like 'curl -k http://192.168.1.9/sleep', to interact with SleepOnLan  https://github.com/SR-G/sleep-on-lan

Is this currently possible from the shutdown section, or could this be enabled in a future version?

**Comment by seriousm4x** [comment]
I can just add the curl package to the container. So you can use curl to make http requests from the shutdown command.

**Comment by bpmarine** [comment]
That sounds perfect - looking forward to the next release
