### ISSUE TITLE
WebUI Not Loading, Connection Refused in Logs

### ISSUE THREAD

**Issue by stephendt** [seriousm4x/UpSnap#25]
Hey guys. A bit of a Docker noob, but struggling to get this operational on my network. I have deployed this within Portainer, and Upsnap doesn't seem to want to run properly. I keep getting a "connection refused" error in the logs. The only thing I've done is define the environment variables so that I am running on a different port, as port 8000 was taken by Portainer itself. Any ideas? Here's a screenshot of the logs: https://i.imgur.com/9rWGJQR.jpeg

Edit: here is what the WebUI looks like: https://i.imgur.com/akMpb7X.jpeg

**Comment by seriousm4x** [comment]
It can't reach the redis container as it says in the logs.
Can you show you config?
