### ISSUE TITLE
Discovery in subnet without zero at the end

### ISSUE THREAD

**Issue by SoulEater45** [seriousm4x/UpSnap#26]
I am currently trying to set up upsnap at work and having trouble to enable network discovery. We only have a fraction of an IP range, lets say `10.0.0.128/26`. If I try to enter it in upsnap it says **Please match the requested format**. Does it expect a zero at the end? I tried also `10.0.0.0/24` and even then I don't get any output, but even if it would output something, I do not want to get results from other departments. `nmap -sn 10.0.0.128/26` gives me the desired range, while `nmap -sn 10.0.0.0/24` also works, but I also get devices that I do not care about.

**Comment by seriousm4x** [comment]
It's currently matching the ip against a regex expression (done in html's "pattern" tag) which requires a 0 at the end and then passes the value to nmap.
When creating this, I tried to make sure people don't put in wrong values. But if its creating too much problems I'm also fine with removing the pattern.
As a quick workaround you can probably open up the browser dev tools on the input field and remove the pattern tag.

**Comment by SoulEater45** [comment]
Thanks for the tip, by removing the pattern tag I was able to add our "exotic" subnet and I am able to scan the network nicely.
I don't mind removing the tag since it has to be done only once. Would be nice if it was mentioned in the readme, or the `zero` at the end could be omitted.

Btw, one more question: if a device gets a new IP from the DHCP, will it automatically update in the dashboard (using the MAC address entry), or do I need to manually change it?

**Comment by SoulEater45** [comment]
Looking forward to that feature! :D

P.S. if I'm already making small requests, I would also add a small comment section for each device to the wish list. It could be used to manage who is currently owning/using it or what kind of device is it (server, workstation, personal machine, phone, etc.).

**Comment by seriousm4x** [comment]
I've removed the regex checks in the frontend. You can now use whatever mac or ip you want.
