### ISSUE TITLE
[REQUEST] Add an optional verification dialog to the manual shutdown command

### ISSUE THREAD

**Issue by stolp** [seriousm4x/UpSnap#260]
**The problem you currently have with this project**
Sometimes I accidently shutdown a computer by clicking on the on/off switch.

**Describe the solution you'd like**
It would be great if a verification dialog would be shown asking if I really want to do that.
Maybe the best way to implement is that the user may choose whether this dialog is shown or not on a per computer basis.

**Comment by duchenpaul** [comment]
Yes! I hope the confirmation can be configurable. Even for the power on button, it is good to have a double confirmation design.

It does not have to be a dialogue, if it could be a "Hold-2-second" to execute or a bar side to execute etc. I would love it more.

**Comment by seriousm4x** [comment]
I've added an optional confirmation dialog for both, wake and shutdown:

<details>
<summary>Screenshots</summary>

![image](https://github.com/seriousm4x/UpSnap/assets/23456686/0fba63a1-a75b-4956-bf9c-5d7d342a2c90)
![image](https://github.com/seriousm4x/UpSnap/assets/23456686/45368624-d69b-407d-b523-1ee1ece9d42e)
![image](https://github.com/seriousm4x/UpSnap/assets/23456686/28cb5509-f423-4729-ba52-8ade119a0096)
</details>

Request to all the translators (@DimitriDR @denymz @MadTiago ):
Could you look over my translations for my commit and tell me if it's correct? I've used DeepL.
https://github.com/seriousm4x/UpSnap/commit/2d7d1119d4365af35296e312c5dc998fdfe8344f#diff-b0073a7fb94f9afda9b390cc757fe4182a8a0642200c0a38b6f22a8a20797087

**Comment by DimitriDR** [comment]
@seriousm4x Translation looks nice on my side 😃
