### ISSUE TITLE
[BUG] button stuck in "Pending" state after shutdown

### ISSUE THREAD

**Issue by rbnet** [seriousm4x/UpSnap#266]
**Describe the bug**
I configured the shutdown of a client using sshpass. Once I click on the client button to shutdown, the command is sent correctly, the client shuts down, but the countdown on the button remains active indefinitely, with the button stuck in "Pending" state. There is no way to get out of this state except by restarting the container even disconnecting and then reconnecting does not solve the problem.

**To Reproduce**
- Add a client
- Configure client shutdown
- Perform shutdown by pressing the client button on the main interface
- Button remains stuck in "pending" state. It is not possible to use the button to wake up the client, and it is not possible to exit this state except by restarting the container.

**Expected behavior**
The button should show the client as off and ready to be awakened via WOL.

**Logs**
There is no relevant log provided by the container

```
[INFO] 2023/10/16 14:04:48 pb.go:258: Ping interval set to @every 10s
2023/10/16 14:04:48 Server started at http://0.0.0.0:8090
├─ REST API: http://0.0.0.0:8090/api/
└─ Admin UI: http://0.0.0.0:8090/_/
[INFO] 2023/10/16 14:08:49 wake.go:12: wake triggered for nas-omv.lan
[INFO] 2023/10/16 14:10:51 shutdown.go:15: shutdown triggered for nas-omv.lan
```

**Screenshots**
Button in normal state with client powered off
![Schermata del 2023-10-16 14-07-59](https://github.com/seriousm4x/UpSnap/assets/15607163/ca07bf8e-06a2-4265-bef1-46615f2a9410)

Button in normal state with client on
![Schermata del 2023-10-16 14-10-49](https://github.com/seriousm4x/UpSnap/assets/15607163/9cdd533e-18ac-48ec-b7d6-c03b8882c03a)

Button stuck in PENDING state after sending the shutdown command to the client (here more than 5 minutes have already passed since sending the shutdown, even waiting longer the button always remains in this state).
![Schermata del 2023-10-16 14-16-14](https://github.com/seriousm4x/UpSnap/assets/15607163/23a3b86f-d8f7-4912-ae39-f991ea629320)

**Host OS (and version)**
Raspberry OS (bullseye) arm64 - Docker version 24.0.6 - Portainer CE 2.19.1 - Image upsnap:latest  

**Host Architecture**
arm64

**Browser (if relevant)**
Brave 1.59.117, Firefox 118.0.2, Chrome 118.0.5993.70

**Additional context**
In the old bug fixes, I found this one in version 4.0.0 that perhaps refers to the same error https://github.com/seriousm4x/UpSnap/commit/05686bf271f47beb14d047932a4c9715d0f53d20

**Comment by rbnet** [comment]
Actually the countdown is correctly shown from 02:00 until 00:00, where it then gets stuck. If I then change to a different page and then return to the Dashboard it is displayed as per the image I attached earlier.

No errors in the console.

**Comment by seriousm4x** [comment]
I took another look at your Docker logs. I noticed that after the last line

```bash
[INFO] 2023/10/16 14:10:51 shutdown.go:15: shutdown triggered for nas-omv.lan
```

there should have been an error like:

```bash
[ERROR] 2023/10/16 14:12:51 shutdown.go:50: nas-omv.lan not offline after 2 minutes
```

But it's not there. Is it possible that your command hangs and does not exit? That would explain why there is no error message afterwards and the timer does not get a new status.

I can also reproduce this when I set the shutdown cmd to `sleep 300`. Then the command is not done within the 2 minutes and the timer stops at `00:00` and displays `  :  ` as soon as the page is reloaded. Exactly as you described it.

I have made a few changes so that the command is always killed after 2 minutes and is not stuck endlessly.

Could you try the new beta if that fixes it for you? [4.1.2-beta.1](https://github.com/seriousm4x/UpSnap/releases/tag/4.1.2-beta.1)

**Comment by rbnet** [comment]
You are right, it is ssh that hangs after the connection drops, I verified this by executing a shell in the container. The problem is the Debian server not properly closing the connection and so the client gets stuck. I couldn't solve it server-side, but from the client just add these two more parameters to the command passed by Upsnap:

```
ServerAliveInterval
ServerAliveCountMax

```

Actually it would be enough to set only the first one, taking into account that the second one defaults to **3**, so the shutdown command becomes something like:

```
sshpass -p password ssh -o ServerAliveInterval=5 -o StrictHostKeyChecking=no user@xxx.xxx.xxx.xxx "sudo poweroff"
```

And the connection is forcibly shut down after about 15 seconds, allowing Upsnap to update its GUI.

The **new build** works fine without any additional parameter (maybe "too much"? The button changes state even before the server has shut down), it does carry a small problem though: every time I turn off that particular server, it creates a zombie process in Upsnap and I don't think this is ok for container performance in the long run.

In the screenshot the 3 zombie processes appeared after 3 shutdowns of the nas-omv.lan device. The shutdown of the other device does not cause any problems.

![Schermata del 2023-10-18 11-06-46](https://github.com/seriousm4x/UpSnap/assets/15607163/4ef5d1b4-80ff-46c6-867b-a641f245beda)

**Comment by rbnet** [comment]
I don't know... I did some more tests and the result is always the same. When the connection to the server hangs, the ssh process remains as a zombie.
A while back I read something about docker and zombie processes and someone had mentioned **dumb-init**. Following the instructions on the project page, I tried using it by building a new image starting from 4.1.2-beta.1. Indeed with my image there are no more zombie processes, but, to put it mildly, I'm not very familiar with docker, so I am not sure if this information is relevant...

**Comment by rbnet** [comment]
No, same result as with the previous beta. The ssh process turns into zombie as soon as sshpass is killed.
I recreated the condition with a `sleep 180` instead of "poweroff" in the shutdown command: after the countdown reached 00:00 sshpass disappears from the list of active processes and ssh turns into a zombie.

**Comment by seriousm4x** [comment]
It turns out that SIGKILL does not terminate all child processes. I changed it to use SIGTERM first, and if that doesn't work, then SIGKILL.

This fixes the problem.
