### ISSUE TITLE
[BUG] Does Not Wake Up

### ISSUE THREAD

**Issue by Ashkaan** [seriousm4x/UpSnap#283]
**Describe the bug**
When attempting to wake up a computer via UpSnap, it does not wake up.
When attempting to wakt up the same computer with WakeMeOnLan, it wakes up.

**To Reproduce**
1. Turn off computer.
2. Press the Red power button on the configured computer in UpSnap

**Expected behavior**
The computer to wake

**UpSnap version**
3.3.0

<img width="2060" alt="image" src="https://github.com/seriousm4x/UpSnap/assets/5667978/5d22c74d-a8b5-4225-a3f6-db8a183f885f">

**Host OS (and version)**
Docker

**Host Architecture**
amd64

**Brower (if relevant)**
Chrome

**Comment by seriousm4x** [comment]
Can you give more info or any clues about where the problem might be? It's really tough to figure this out without some additional details.

**Comment by seriousm4x** [comment]
You can try a wol packet sniffer like [wake on lan monitor](https://www.depicus.com/wake-on-lan/wake-on-lan-monitor) to see if the pc actually receives the wol packet. Make sure to set UDP port 9 before starting

**Comment by Ashkaan** [comment]
It's not sending anything to the computer.

<img width="433" alt="image" src="https://github.com/seriousm4x/UpSnap/assets/5667978/bdb50ba3-db3a-4ad0-a923-03bc5513abf9">

**Comment by seriousm4x** [comment]
It's really hard to debug this. Try to set the device's netmask to 255.255.255.255 and try again.
If that doesn't work either, I assume other programs do some additional things besides sending a package to port 9.

**Comment by Ashkaan** [comment]
I was using 255.255.255.0 because that's the mask of the subnet.  It's just a simple, /24, flat network.  Totally vanilla.

Yes, Ok!  I'll use this moving forward.  Thank you
