### ISSUE TITLE
[REQUEST]Whether it is possible to run in a container with bridge network

### ISSUE THREAD

**Issue by qianhd** [seriousm4x/UpSnap#291]
**The problem you currently have with this project**

For some reason, I am unable to use the host network mode. 
so i modify docker-compose.yaml file by removing the line of “network_mode: host”. 
I know this will causes the wol to be unavailable. (because the udp broadcast packet cannot cross docker bridge network)
then i try to modify iptables rule, like using SNAT to change src of the wol package (-j SNAT --to-source xxx.xxx.xxx.xxx), but it's also useless. 

**Describe the solution you'd like**
I want to know why iptables rule is useless. is that my misconfigured it or it's impossible. and why?

**Additional context**

**Comment by seriousm4x** [comment]
That's a question I can't answer. I have close to zero experience with iptables.

**Comment by qianhd** [comment]
> That's a question I can't answer. I have close to zero experience with iptables.

Well, thank you for making such an awesome software
