### ISSUE TITLE
[REQUEST]How to build a linux_mips version binary

### ISSUE THREAD

**Issue by lushtech** [seriousm4x/UpSnap#316]
**The problem you currently have with this project**
I want to use binary in my router, my router is base on mips

**Describe the solution you'd like**
I want to build a binary base on mips

**Additional context**
Could you help me ?

**Comment by seriousm4x** [comment]
I don't have a mips device to test this, but it should be possible. One thing: you have to enable C go to build the binary, so you have to build it on the same device as you will run it on (your router).

You can use [Dockerfile.dev](https://github.com/seriousm4x/UpSnap/blob/master/Dockerfile.dev) as a template.

Basically clone the repo, install npm and go 1.21 and then run:

```bash
# install pnpm
npm i -g pnpm

## build frontend
cd frontend &&\
pnpm i &&\
pnpm run build &&\
mv -R build/* ../backend/pb_public/

# build binary
cd backend &&\
CGO_ENABLED=1 go build -o upsnap main.go &&\
chmod +x upsnap
```

**Comment by lushtech** [comment]
@seriousm4x Thank you.

I tested it in these days, and it works but confront some problems.
 
The compilation steps are as follows:

- Step one: Confirm the architecture of my router.
my router is xiaomi router 3. Through its official documentation at http://www1.miwifi.com/miwifi_open.html, I flashed the development version of the firmware and enabled SSH access.  
And I confirmed the required architecture information for compilation as follows: The chip is MediaTek's MT7620A, belonging to the 32-bit MIPS architecture, single-core, little endian, without an FPU unit. The operating system is based on OpenWRT's Linux version, and the library is uclibc.


- Step two: Set up the cross-compilation environment.
**About gcc** 
For my Xiaomi Router 3, the official site offers a toolchain for compilation. It can be obtained from the website http://www1.miwifi.com/miwifi_open.html. By clicking on "Product Development Documentation" and selecting the corresponding router model (e.g., R3), download the compressed file named sdk_package_r1c.zip. Once extracted, within the sdk_package_r1c/toolchain/bin directory, you'll find mipsel-openwrt-linux-uclibc-gcc, which is the GCC compiler we need.
**About goloang**
You can refer to this article: [Install Go (1.21.0) in Ubuntu 22.04.2 in 5 minutes.](https://royzsec.medium.com/install-go-1-21-0-in-ubuntu-22-04-2-in-5-minutes-468a5330c64e)
- Step three: Obtain the source code for compilation.
**install pnpm**
   ```
   npm i -g pnpm
   ```  
   **build frontend**
   ```
    git clone https://github.com/seriousm4x/UpSnap

    cd UpSnap/frontend &&\
    pnpm i &&\
    pnpm run build &&\
    mv -r build/* ../backend/pb_public/
   ```
   **build binary**
   ```
   cd backend &&\
   CGO_LDFLAGS="-L/home/lee/Downloads/sdk_package_r1c/toolchain/bin" 
   CC=/home/lee/Downloads/sdk_package_r1c/toolchain/bin/mipsel-openwrt-linux-uclibc-gcc  CGO_ENABLED=1 GOOS=linux 
   GOARCH=mipsle GOMIPS=softfloat go build -ldflags="-s -w" -o upsnap-with-s-w &&\
   chmod +x upsnap-with-s-w
    ```
    Using the -s and -w options removes symbol table and debugging information, resulting in a smaller binary file. Without these parameters, the file size is 74MB, and with -s -w options, it reduces to 41MB.

     **up the file to the router and run**
     ```
     chmod +x  upsnap-with-s-w
    ./upsnap-with-s-w serve --http=0.0.0.0:8090
    ```
     **After running，screenshot on the browser, screenshots of router directory, and SSH interface**
      screenshots of SSH interface
      ![command](https://github.com/seriousm4x/UpSnap/assets/46964559/8fb74f28-094e-4c55-ab0b-4ae2621370a2)
      screenshots of the browser
      ![login_admin](https://github.com/seriousm4x/UpSnap/assets/46964559/c769944a-2eac-48ce-9734-bc51b25ff469)
      ![login](https://github.com/seriousm4x/UpSnap/assets/46964559/8d370389-109d-4d3e-a7ae-e70b09a3b90e)
      ![after_login](https://github.com/seriousm4x/UpSnap/assets/46964559/e3083a1f-1d72-4e3f-b27d-13fc643da014)
      screenshots of router directory
      ![command1](https://github.com/seriousm4x/UpSnap/assets/46964559/a1b5e2f3-853d-48dc-9196-9f16565b15e4)
      ![command2](https://github.com/seriousm4x/UpSnap/assets/46964559/22027170-5c83-4c8a-a9d7-3988aa94379c)

**Encountered issue 1:** After creating the admin account, unable to log in from ip:8090/_/. Upon entering the correct username and password, it redirects back to the login interface. Only able to log in from ip:/8090/login."

**Encountered issue 2:** It seems that there's a lack of static files, as the pb_public-related files cannot be found in the router's upsnap running directory.

Additionally, I have not conducted network wake-on-LAN power on/off tests yet.

**Comment by seriousm4x** [comment]
It's cool that you've made it this far! About your two issues: Unfortunately I can't test this as I don't have any devices on this platform.

1. Everything that runs under `/_/` belongs to [PocketBase](https://github.com/pocketbase/pocketbase). If the same problem exists with the official PB binary, you would have to create an upstream issue.
2. I don't quite understand why the static files were not found. In your screenshot of the login you can see the logo which belongs to the assets. So it is found or not?

**Comment by lushtech** [comment]
I tested it again, and it works well. I can login ip:8090/_/ as admin and ip:/8090/login as a user.
About the missing static files , I think that  it be included in the binary, Because  the web page looks normal.
The issue has been resolved now. I suggest closing this request.
@seriousm4x Thank you.
