### ISSUE TITLE
API available?

### ISSUE THREAD

**Issue by dimatx** [seriousm4x/UpSnap#32]
Hi there,

Thanks for your contributions with UpSnap. I'm looking to use UpSnap to wake one of my PC as part of a home automation routine. Is there an endpoint that I can call (instead of using the UI) to have UpSnap send a WOL packet to a PC?

Thanks!

**Comment by seriousm4x** [comment]
Hi,
Currently not. I'm using websockets for the whole thing, so there are not http endpoints.
I'm working on a go rewrite though, which it will make possible. Look out for v3 to be released. Won't be long.

**Comment by dimatx** [comment]
Thanks!

**Comment by seriousm4x** [comment]
Api is now available in the v3 beta release. I will add some documentation later on in the wiki.
https://github.com/seriousm4x/UpSnap/releases/tag/v3.0.0-beta.1

**Comment by seriousm4x** [comment]
https://github.com/seriousm4x/UpSnap/wiki/Rest-API
