### ISSUE TITLE
Seemingly High Ram usage

### ISSUE THREAD

**Issue by hydrian** [seriousm4x/UpSnap#33]
I just deployed UpSnap stock (sqlite) docker image and I like it. When I looked at the ram usage, The upsnap_app is using  561MB of used memory and 101MB of cache. This is with just one device added to it. I find it hard to believe that a simple web interface and a scheduler need that much ram. The Reddis instance is only taking about 12MB (Usage + cache). 

I'm not saying the code is bad. I'm saying that probably the internal DJANGO service needs to be tweaked for more realistic RAM usage.

**Comment by hydrian** [comment]
I'm using the amd64 docker-compose from this github repo.

**Comment by seriousm4x** [comment]
Hi there. Django in combination with celery and redis is known to use a lot of ram. I've read something about reducing workers, but likely I won't change anything to v2 as I'm currently working on [v3](https://github.com/seriousm4x/UpSnap/tree/v3) which is written in go. (If you find some quick and easy improvements, let me know.)
v3 currently uses around 13mb (although not all features are inplementet yet).
I hope it will only take a few more days until I can get a first release candidate out.

**Comment by hydrian** [comment]
Yea. the redis container isn't the problem. It is running in a very reasonable about of ram. I think the biggest thing is the number of workers. I think we could reduce down to 2 and still be find. I'll do some looking into it.

**Comment by hydrian** [comment]
I dropped the works from 4 to 2 in run.sh. That dropped the RAM usage from about 561MB to about 422mb usage and 26MB cache. Not great but better.

**Comment by seriousm4x** [comment]
Api is now available in the v3 beta release. I will add some documentation later on in the wiki.
https://github.com/seriousm4x/UpSnap/releases/tag/v3.0.0-beta.1
