### ISSUE TITLE
[Enhance] Add support for WOL passwords

### ISSUE THREAD

**Issue by hydrian** [seriousm4x/UpSnap#34]
I've assuming this is going to be for V3 but it would be nice to be able to set per-device WOL passwords.

**Comment by seriousm4x** [comment]
I didn't know that you can set a password for wol. Is this done in the bios? Is there documentation for this?

**Comment by hydrian** [comment]
It is usually in the motherboard bios for integrated LAN cards. I maybe some PCIe NICs that actually have a BIOS. I think I've seen them there too.

From the client side, look at man pages for  etherwake.

**Comment by hydrian** [comment]
It is usually in the motherboard bios for integrated LAN cards. I maybe some PCIe NICs that actually have a BIOS. I think I've seen them there too.

From the client side, look at man pages for  etherwake. You can set the WOL SecureOn password with the ethtool parameter ``sopass``

**Comment by seriousm4x** [comment]
https://github.com/seriousm4x/UpSnap/releases/tag/v3.0.0-beta.1
