### ISSUE TITLE
Install docker in Unraid

### ISSUE THREAD

**Issue by joaoferreira-git** [seriousm4x/UpSnap#38]
Hello, I'm trying to install this in unraid but so far i can't seem to get it working.

This is my current config based on a automatic template created by Unraid and it looks like im missing something for the redis.
What do i need to add to the template to get it working?
Pass a env so that i can point the redis ip:port to the redis container i have already installed?

![image](https://user-images.githubusercontent.com/19786598/216706078-b265aa0b-ecf7-4a89-89bb-f675257cbee4.png)

Log 

```up to date, audited 155 packages in 902ms

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> svelte-app@1.0.0 build
> rollup -c


> svelte-app@1.0.0 start
> sirv public --no-clear --host


  Your application is ready~! 🚀

  - Local:      http://0.0.0.0:8080
  - Network:    http://172.17.0.4:8080

 LOGS 

[2023-02-03 20:38:15,997: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: Error 111 connecting to 127.0.0.1:6379. Connection refused..
Trying again in 6.00 seconds... (3/100)

[2023-02-03 20:38:22,003: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: Error 111 connecting to 127.0.0.1:6379. Connection refused..
Trying again in 8.00 seconds... (4/100)

[2023-02-03 20:38:30,011: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: Error 111 connecting to 127.0.0.1:6379. Connection refused..
Trying again in 10.00 seconds... (5/100)
```

If i try to open the web ui i get a white page but it's showing the correct logo in the browser tab 
![image](https://user-images.githubusercontent.com/19786598/216706725-6207e2a5-d062-4f0a-98f2-a47a8abed8fa.png)

**Comment by seriousm4x** [comment]
Hi, you are trying to use hub.docker.com, which is only used for v2 (deprecated).
I moved to ghcr for v3. Also the [readme over there](https://hub.docker.com/r/seriousm4x/upsnap) tells you that ;)
You can find the new one here https://github.com/seriousm4x/UpSnap/pkgs/container/upsnap
