### ISSUE TITLE
Server Error (500) on Docker install

### ISSUE THREAD

**Issue by jackald** [seriousm4x/UpSnap#4]
I have just tried this and the Postgres database has the below error

> 2021-10-01 12:51:13.657 UTC [539] ERROR:  relation "wol_websocket" does not exist at character 62,
> 2021-10-01 12:51:13.657 UTC [539] STATEMENT:  SELECT "wol_websocket"."id", "wol_websocket"."visitors" FROM "wol_websocket" ORDER BY "wol_websocket"."id" ASC LIMIT 1,
> 2021-10-01 12:51:12.655 UTC [538] STATEMENT:  SELECT "wol_websocket"."id", "wol_websocket"."visitors" FROM "wol_websocket" ORDER BY "wol_websocket"."id" ASC LIMIT 1,
> 2021-10-01 12:51:12.655 UTC [538] ERROR:  relation "wol_websocket" does not exist at character 62

The django container is erroring with the below:

> [2021-10-01 13:52:36,727: ERROR/ForkPoolWorker-2] Task wol.tasks.scheduled_wakes[939342b1-1eb9-4f19-9cdb-9a0efe01fff2] raised unexpected: ProgrammingError('relation "wol_websocket" does not exist\nLINE 1: ..._websocket"."id", "wol_websocket"."visitors" FROM "wol_webso...\n                                                             ^\n'),
> Traceback (most recent call last):,
>     return self.cursor.execute(sql, params),
>   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute,
> psycopg2.errors.UndefinedTable: relation "wol_websocket" does not exist,
> LINE 1: ..._websocket"."id", "wol_websocket"."visitors" FROM "wol_webso...,
> ,
>                                                              ^,
> The above exception was the direct cause of the following exception:,
>   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 450, in trace_task,
>     R = retval = fun(*args, **kwargs),
>   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 731, in __protected_call__,
>     return self.run(*args, **kwargs),
>   File "/app/wol/tasks.py", line 74, in scheduled_wakes,
>     if Websocket.objects.first().visitors == 0:,
>   File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method,
>     return getattr(self.get_queryset(), name)(*args, **kwargs),
>   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 674, in first,
>     for obj in (self if self.ordered else self.order_by('pk'))[:1]:,
>     self._fetch_all(),
>   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 280, in __iter__,
>   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all,
>   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__,
>     self._result_cache = list(self._iterable_class(self)),
>     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size),
>     cursor.execute(sql, params),
>   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql,
>   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute,
>     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute),
>   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers,
>     return executor(sql, params, many, context),
>   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__,
>     raise dj_exc_value.with_traceback(traceback) from exc_value,
> django.db.utils.ProgrammingError: relation "wol_websocket" does not exist

**Comment by seriousm4x** [comment]
```
File "/app/wol/tasks.py", line 74, in scheduled_wakes,
if Websocket.objects.first().visitors == 0:,
```
Here it's trying to get the current visitors from the database, but it seems there is no entry.
I can't seem to reproduce this on my side. Are there any changes you did to the compose file? What system are you running on?

**Comment by jackald** [comment]
Got it to work for some reason the bind mount I did for the database seemed to fail the first time. I deleted the folder then had the container restart, and it now works. Thanks

**Comment by seriousm4x** [comment]
Happy to hear ;)
