### ISSUE TITLE
[REQUEST] ipmicfg support

### ISSUE THREAD

**Issue by ironicbadger** [seriousm4x/UpSnap#41]
**The problem you currently have with this project**
It'd be neat if I could issue custom ipmicfg commands via this project.

**Describe the solution you'd like**
`ipmicfg -u user -p pass chassis power on` for example

**Comment by seriousm4x** [comment]
I think the easiest solution is to change the entrypoint in docker-compose. Installing all packages someone might need would make the image unnecessarily large.
I haven't found the correct alpine package for `ipmicfg`, but if there is one, you can install it like so:
```sh
version: "3"
services:
  upsnap:
    image: ghcr.io/seriousm4x/upsnap:3
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data:/app/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
    entrypoint: /bin/sh -c "apk update && apk add --no-cache ipmitool && rm -rf /var/cache/apk/* && ./upsnap serve --http 0.0.0.0:8090"
```
I will add this to the docker-compose.yml as an example.
