### ISSUE TITLE
login for edit settings

### ISSUE THREAD

**Issue by u-name** [seriousm4x/UpSnap#42]
very nice app!
it would be great if only logged in user (admin) could edit settings.
so normal user are only able to wake up there computers - nothing else - without login.
Just one admin/login for adding computer and settings.

**Comment by seriousm4x** [comment]
I'll look into it

**Comment by gaby** [comment]
@seriousm4x Since you are already using `Echo` for the backend. You could integrate [pocketbase.io](https://pocketbase.io/) which also uses `Echo`. It can also be used as a go library more info [here](https://pocketbase.io/docs/use-as-framework/)

**Comment by seriousm4x** [comment]
https://github.com/seriousm4x/UpSnap/issues/55#issuecomment-1455001504
