### ISSUE TITLE
VM Proxmox

### ISSUE THREAD

**Issue by zarevskaya** [seriousm4x/UpSnap#43]
Hi,

Thank you for this amazing app! In first.

I use Proxmox, that work for Proxmox but not for the VM.

Is it possible to add a founction to control the WOL on a VM?

Thank you for reading me.

**Comment by seriousm4x** [comment]
Wake on lan is a network card feature. So if your vm doesn't have its own network card, it won't be possible.
I've found this [proxmox forum post](https://forum.proxmox.com/threads/wake-on-lan-for-vm.84355/). Looks like they have an API to wake VMs. But currently I've only added custom shutdown commands and no wake up commands.

**Comment by zarevskaya** [comment]
Ok, thank you for your post and the link.

Have a nice day :)
