### ISSUE TITLE
Container log contains repeated "database is locked" errors

### ISSUE THREAD

**Issue by QuickJack** [seriousm4x/UpSnap#45]
Container logs contain repeated entries like 

```
[ERROR] 2023/02/06 10:19:44 cronjobs.go:60: database is locked (5) (SQLITE_BUSY)
```

**Comment by seriousm4x** [comment]
I've posted a question on pocketbase's discussions as I'm not sure if its a problem with my code or theirs.
https://github.com/pocketbase/pocketbase/discussions/1795

**Comment by seriousm4x** [comment]
Is there any way to consistently trigger the error? How many devices are you using?

**Comment by QuickJack** [comment]
Currently my database contains 35 machines. Over a period of 3:11h the error was logged 44 times in total. I have opened a browser windows during this time. But as this is a testing instance, it's relatively unlikely that anybody else did access it.

**Comment by seriousm4x** [comment]
Thanks for the info. I've also tried to reproduce it but that error didn't came up since yesterday.
[@gani](https://github.com/ganigeorgiev) (the creator of pocketbase) also looked at this and [responded](https://github.com/pocketbase/pocketbase/discussions/1795#discussioncomment-4882169). I will leave my instance running for a while and continue to observe it.

**Comment by seriousm4x** [comment]
Some more questions:
- Approximately how many ports does each device have?
- What ping interval did you use?
- Is the database on HDD or SSD?

**Comment by QuickJack** [comment]
There are no custom ports defined for any of the devices. I am using the default ping interval of 10 seconds. The database is on HDD.

**Comment by seriousm4x** [comment]
PocketBase has released version [v0.13.0](https://github.com/pocketbase/pocketbase/releases/tag/v0.13.0) which addresses this issue.

> - Added auto fail/retry (default to 8 attempts) for the SELECT queries to gracefully handle the database is locked errors ([#1795](https://github.com/pocketbase/pocketbase/discussions/1795#discussioncomment-4882169)).
The default max attempts can be accessed or changed via Dao.MaxLockRetries.

I've also pushed version 3.0.6. Please try it and tell me if it works better. I still wasn't able to reproduce it though.

**Comment by QuickJack** [comment]
Thanks, I will test it tomorrow.

**Comment by QuickJack** [comment]
This issue seems to be fixed.
