### ISSUE TITLE
WOL does not work

### ISSUE THREAD

**Issue by QuickJack** [seriousm4x/UpSnap#46]
I am currently using v1. I have a testing instance running on v2 (latest) which is working perfectly well. However, after importing hosts data to a v3 instance, WOL is not working anymore.

I have double checked that "netmork_mode: host" is active and that the entries for MAC and IP address are correct.

**Comment by seriousm4x** [comment]
Please stick to the issue template as its very hard for me to reproduce something like this without further infos.
Is there a simple way I can reproduce this?
Have you tried using the [example here](https://github.com/seriousm4x/UpSnap/blob/master/docker-compose.yml) and adding devices manually?

**Comment by QuickJack** [comment]
By using tcpdump I noticed the difference between v2 and v3. The latter is using 10.255.255.255 as destination ip whereas v2 is using 255.255.255.255. I guess this is because the ip of the test machine begins with 10.

**Comment by seriousm4x** [comment]
There was an error with calculating the broadcast address when using `0.0.0.0` as the netmask. For example:
ip: `192.168.0.5` netmask: `0.0.0.0` would return `192.255.255.255` and not `255.255.255.255`.
Can you try with [3.0.4-beta.1](https://github.com/seriousm4x/UpSnap/releases/tag/3.0.4-beta.1)?

**Comment by seriousm4x** [comment]
Should be fixed with 3.0.4
