### ISSUE TITLE
Security Login

### ISSUE THREAD

**Issue by chriswhaas** [seriousm4x/UpSnap#48]
Hi,  thank you for this great project. I installed it on my Synology and it works great in my local network.

Maybe my way of thinking is wrong, but how can i securely use UpSnap over the internet? I can open the ports and use it from outside, should be no problem. But without  login and password, anybody could start my computers, right ? Just a simple port scan and the person could log into UpSnap and modify my systems, correct?

What is you way of solving that kind of problem?

Thank you

**Comment by seriousm4x** [comment]
Hi, yes you understand correctly. Exxposing the ui to the internet is not secure at all. Don't do this.
The recommended way is to use a vpn to your home router/nas/whatever. Don't expose the ports.
