### ISSUE TITLE
[BUG] Authentication improperly persisted

### ISSUE THREAD

**Issue by Doosty** [seriousm4x/UpSnap#481]
### The bug

It seems that refreshing an open browser tab or opening a cached version of Upsnap allows you to sort of stay shadow logged in, even if during that time the original Upsnap process was killed and another was started in its place with a different `--dir`, where that original user does not exist.

### The OS that UpSnap is running on

NixOS

### Version of UpSnap

4.2.7 - latest

### Your docker-compose.yml content

I started off by using a podman config with a 1:1 replica of your example docker-compose config, but have since then packaged the app natively on Nix without containerization. The application is functioning in both cases, with the same issue so i do not think the bug im experiencing has anything to do with how i run it, but i will post my nix configs if you ask it.

### Reproduction steps

1. Start an Upsnap process with a specified `--dir` and create a user.
- `upsnap serve --http 0.0.0.0:8090 --dir /var/lib/upsnap-alice`
- on the webui, create a user with email `alice@email.com`
2. Kill the running process then repeat with a different `--dir` and different user
- `upsnap serve --http 0.0.0.0:8090 --dir /var/lib/upsnap-bob`
- on the webui, create a user with email `bob@email.com`
3. Keep the page open where `bob` is logged in, kill the process, start the process where the user `alice` exists.
- `upsnap serve --http 0.0.0.0:8090 --dir /var/lib/upsnap-alice`
4. Now you can refresh the open web page and will see bob still logged in. You can even navigate between pages and do some stuff, however when i trigger network scan it doesnt work. It seems authentication cookie is not properly validated with each http request. 
5. The same thing happens if i just restart the same process (i am still logged in but with errors when trying to do stuff). However the example with two different `--dir` args and two different users seems the most understandable.

### Additional information

PS: while packaging i noticed that your app creates an empty `$HOME/.config/upsnap` even when providing a custom `--dir`

Otherwise i love the app, thanks for your work!

**Comment by seriousm4x** [comment]
Thanks for reporting. I remember thinking about this scenario when writing the auth refresh code.
The r

**Comment by seriousm4x** [comment]
I remember when I wrote the code for it. But the whole thing is purely cosmetic. The user still has no rights, as the token is invalid against the changed backend.

My thought process back then:

> I first check the expiration date of the token before I check the token against the backend. Otherwise, a token check would be made every time a page is opened. If the date check was not there and the token request fails even once, the user is logged out (this has happened several times). I therefore decided to first check the token for the expiration date and then, if necessary, perform a token refresh to reduce the probability of being logged out.

I'll have to look at the whole thing again. Maybe I can find a better way.
