### ISSUE TITLE
[BUG] Version 3.0.3 not working

### ISSUE THREAD

**Issue by r-bonnes** [seriousm4x/UpSnap#49]
**Describe the bug**
The script not working at all and log an error (see logs section)

**To Reproduce**
1. wget https://github.com/seriousm4x/UpSnap/releases/download/3.0.3/UpSnap_3.0.3_linux_amd64.zip
2. unzip UpSnap_3.0.3_linux_amd64.zip
3. run the command: ./upsnap serve --http=0.0.0.0:8080

**Expected behavior**
The script working and the server running

**Logs**
```
./upsnap: line 3: syntax error: unexpected "("
```

**Screenshots**
![image](https://user-images.githubusercontent.com/72978947/217255525-1c5c382f-11f6-462a-a19d-9a0c55f70745.png)

**Host OS (and version)**
Proxmox Container with Alpine 3.15.6

**Host Architecture**
arm64

**Comment by seriousm4x** [comment]
You are downloading the amd64 version but try to run it on arm64.
Make sure to download the correct one https://github.com/seriousm4x/UpSnap/releases/download/3.0.3/UpSnap_3.0.3_linux_arm64.zip

**Comment by r-bonnes** [comment]
Same problem. I did not get the wrong package I confirm. I downloaded the 3.0.2 amd64 version and everything works. The problem comes from the version and not from the architecture.

**Comment by seriousm4x** [comment]
Ok, so I installed proxmox 7.3 (amd64) in a vm, created an alpine 3.15 container and downloaded upsnap version 3.0.3, extracted it and it works...

![2023-02-08 21_21_52](https://user-images.githubusercontent.com/23456686/217642660-eb86eda6-ab40-4b72-a895-ae8570ecc5ca.png)

I'm not quite sure what's not working for you.

**Comment by r-bonnes** [comment]
Ok well, i reinstalled it and it's working now. i don't understand what was the probleme.
