### ISSUE TITLE
[Feature Request] Edit existing devices

### ISSUE THREAD

**Issue by Forger125** [seriousm4x/UpSnap#5]
Hi @seriousm4x, thank you for making such a fantastic and useful project and for contributing it  to the community!

One feature which might be nice to add is a GUI option to edit existing devices. For example, several devices on my network get added with the name "Unknown." It would be nice to have an option to edit the various fields (Name in this case, but also IP and MAC address) after the fact.

Thanks again!

**Comment by seriousm4x** [comment]
Yes, it's a good idea. In the meantime you can also change the names in the backend under `/admin/`.

**Comment by Forger125** [comment]
:clap: thank you! @seriousm4x
