### ISSUE TITLE
Power button triggers a loop. DOES succesfully wake on lan, but UpSnap doesn't find out, so it keeps pinging endlessly.

### ISSUE THREAD

**Issue by jordantgh** [seriousm4x/UpSnap#53]
**Describe the bug**
Clicking power button in the frontend app causes a loop to occur. My target (Windows 11) PC wakes up, but it seems my UpSnap instance can't see that information. On the terminal where I am serving the it, the ping comes out as:

`ping.go:23: listen ip4:icmp : socket : operation not permitted`

this repeats until:

`handlers.go:27: JT Home%!(EXTRA string=not online after 2 min)`

**Host OS (and version)**
Ubuntu 22.04

(targetting a Win11 for WoL)

**Comment by seriousm4x** [comment]
Thats probably because you are not running it as root. Pinging creates a raw socket to send the ping. Raw sockets are only allowed to privileged users. Try it with sudo and see if that helps.

**Comment by jordantgh** [comment]
It did, thanks for the fast responses. I looked up as well online after that and found out that I could set permissions to avoid needing to run as root with `sudo setcap cap_net_raw+ep ./upsnap`, incase that might be useful for someone else as novice as me.

Cheers for the cool software.
