### ISSUE TITLE
[BUG] Unable to login or create users with existing database

### ISSUE THREAD

**Issue by beastarman74** [seriousm4x/UpSnap#57]
**Describe the bug**
System auto-updated to the latest release. When opening the application website, I am presented with the new login screen. I followed the documentation to visit the Pocketbase interface to create an account.

However there is no option presented to create an account. 

![Resizer_16780417510921](https://user-images.githubusercontent.com/44511355/222982467-19a69812-a2ae-48ce-a639-cdfb3e8247c7.png)

If I start a clean instance to setup from scratch and visit the Pocketbase interface it does provide the option to create an account.

![Resizer_16780460968221](https://user-images.githubusercontent.com/44511355/222982658-8f5199df-1731-458c-94ef-552ff3a39495.png)

**To Reproduce**
1. Upgrade an existing UpSnap instance to latest version 
2. Click on manage users on login prompt
3. Pocketbase interface does not offer an option for account creation and does not accept any entry

**Expected behavior**
UpSnap upgrades an existing instance and allows creation of user account in the Pocketbase interface.

**Logs**
There is nothing of note in the logs
![Screenshot_20230305_195636](https://user-images.githubusercontent.com/44511355/222982763-e5a20bec-3089-4619-bd9e-85cb4c70c7a4.png)

**Host OS (and version)**
File: /etc/os-release
   1   │ PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
   2   │ NAME="Debian GNU/Linux"
   3   │ VERSION_ID="11"
   4   │ VERSION="11 (bullseye)"
   5   │ VERSION_CODENAME=bullseye
   6   │ ID=debian
   7   │ HOME_URL="https://www.debian.org/"
   8   │ SUPPORT_URL="https://www.debian.org/support"
   9   │ BUG_REPORT_URL="https://bugs.debian.org/" 

**Host Architecture**
arm64

**Brower (if relevant)**
n/a

**Additional context**
n/a

**Comment by seriousm4x** [comment]
> **To Reproduce** Steps to reproduce the behavior:
>     1. Upgrade an existing UpSnap instance to latest version
>     2. Click on manage users on login prompt
>     3. Pocketbase interface does not offer an option for account creation and does not accept any entry

Hm, I downloaded version 3.0.6 and set it up from scratch (without creating an account). After that I downloaded 3.1.0 and ran it. Now when I visit the Pocketbase dashboard, I am prompted to create a new account.

Are you sure you didn't create an admin account on an older version before?

**Comment by beastarman74** [comment]
I am sorry, you are right, I must have created one earlier but I could not recollect doing so. I can't believe, I have wasted your time. Sorry again

**Comment by seriousm4x** [comment]
No problem 😄
