### ISSUE TITLE
Docker container fails to start 

### ISSUE THREAD

**Issue by sunny5055** [seriousm4x/UpSnap#6]
Getting below error with the latest Docker image

django.db.utils.OperationalError: SCRAM authentication requires libpq version 10 or above

tried changing postgresql authentication to md5 does not seem to work. Also tried to use posgresql 14 but doesnt work.

**Comment by seriousm4x** [comment]
I've release a new version. The docker-compose file changed and it now uses postgres 14.

Let me know if it works now

**Comment by sunny5055** [comment]
Thanks. Just gave it a try. Still has same issue..

django.db.utils.OperationalError: SCRAM authentication requires libpq version 10 or above

**Comment by seriousm4x** [comment]
I need a little background. What system are you running on? What are the steps the reproduce this?

**Comment by sunny5055** [comment]
am using ubuntu. i just ran the docker-compose from the sample.

Also on a side note can you make these as env variables for postgres

        "HOST": "127.0.0.1",
        "PORT": 5432,

and this one for redis
CELERY_BROKER_URL = "redis://127.0.0.1:6379"

These ports are already utilized on my host and I cant update it.

**Comment by seriousm4x** [comment]
So I think the problem is that upsnap tries to connect to the already running database on your host and fails when connecting. That's what's causing the error, right?

I can set the host and port as a env variable. That's no problem.

**Comment by sunny5055** [comment]
Yes may be that might be the reason. I tried removing host network but since the environment variable is not set. It didn't work out. 
Let me know once you have new build with the env var added. I will give it a try..

**Comment by seriousm4x** [comment]
new version available. redis and postgres now both have env vars. update your compose file

**Comment by seriousm4x** [comment]
Hm, ok. Lets try to install libpq5 in the django container. Can you please try the following?

* clone the repo
* then in Dockerfile [L22](https://github.com/seriousm4x/UpSnap/blob/master/Dockerfile#L22) add `libpq5` to installed packages
* and in docker-compose.yml, change [L5](https://github.com/seriousm4x/UpSnap/blob/master/docker-compose.yml#L5) to `build: .`

Then start the container again. If that not helps, I don't know :/

**Comment by sunny5055** [comment]
I have given it a try and no of work arounds but nothing seems to work.  

When i checked what version of libpq is present it seems to be latest 
Step 10/16 : RUN dpkg -l | grep libpq
 ---> Running in 275ee0a49d00
ii  libpq-dev                  13.5-0+deb11u1                 arm64        header files for libpq5 (PostgreSQL library)
ii  libpq5:arm64               13.5-0+deb11u1                 arm64        PostgreSQL C client library


I found out its an issue with base image for arm64 while there is no issue for amd 
Refer to this link for similar issue 
https://stackoverflow.com/questions/69573312/python-psycopg2-scram-authentication

So may be need to pick another base build ?

**Comment by seriousm4x** [comment]
So I was able to reproduce this issue in a arm64 VM. Turns out debian actually uses an outdated version.
I've changed the docker image to alpine. It worked in my arm64 VM and on my host amd64.
v1.2.2 is building now.

**Comment by sunny5055** [comment]
Thanks the new image does have the error anymore. 
django started well without any error but the port is not published to access the web ui. below is the log
https://pastebin.pl/view/8fdd1c03

**Comment by sunny5055** [comment]
I got it sorted out. you can close this issue 👍  thanks for your support
