### ISSUE TITLE
How To Disable Authentication ?

### ISSUE THREAD

**Issue by drtech981** [seriousm4x/UpSnap#60]
I use Authelia to authenticate my logins, and having another login layer behind is just redundant.
Is there any option to disable the inbuilt authentication ?

**Comment by seriousm4x** [comment]
My first implementation tried to achieve this via an environment variable, but it was causing too much issues. Therefore i went with this approach.

However, another thing you could to, is to raise the time your login is valid, so you can login once and that session will be valid for like 1 year. You can do so at [http://localhost:8090/_/#/settings/tokens](http://localhost:8090/_/#/settings/tokens).
For users set `Auth record authentication token duration (in seconds)` and for admins `Admins auth token duration (in seconds)`. So you could set those to `31536000` seconds (1 year). Default value is 14 days.

**Comment by drtech981** [comment]
Okay, but there's no way to turn off authentication at this time right ?

**Comment by seriousm4x** [comment]
No, currently not.

**Comment by diamondsw** [comment]
So I come back to a nice and simple tool that used to work and am presented with a login page that I have no record of and no credentials for. Just automatically defaulted on, no first-run wizard or anything, just "hey, you're locked out".

Oh well, It was a nice tool. Deleted.

**Comment by seriousm4x** [comment]
> So I come back to a nice and simple tool that used to work and am presented with a login page that I have no record of and no credentials for. Just automatically defaulted on, no first-run wizard or anything, just "hey, you're locked out".
> 
> Oh well, It was a nice tool. Deleted.

Creating credentials is as easy as

* Click `Manage users` at the buttom of the login form
* Put in your new admin email and password (doesn't even need to be a real email)

I thought it's easy enough to understand. Apperently not.
