### ISSUE TITLE
Chrome won't allow download on windows because of anti virus / defender

### ISSUE THREAD

**Issue by bn-l** [seriousm4x/UpSnap#685]
### The bug

Chrome:
![image](https://github.com/user-attachments/assets/9622985d-2bad-4d25-9fda-9dc3c8a3bc03)

Windows defender:
![image](https://github.com/user-attachments/assets/fa9a2595-e30d-4f05-9ebb-a24a00d8d9b2)

### The OS that UpSnap is running on

Windows 10 Pro 22H2

### Version of UpSnap

4.2.12

### Your docker-compose.yml content

```YAML
n/a
```

### Reproduction steps

```bash
1. Use Windows 10 Pro 22H2 and chrome 126.0.6478.182
2. Attempt to download https://github.com/seriousm4x/UpSnap/releases/download/4.2.12/UpSnap_4.2.12_windows_amd64.zip
```

**Comment by seriousm4x** [comment]
Can't reproduce it on Win 11 with chromium 127.0.6533.72
