### ISSUE TITLE
[BUG] Icon change not possible

### ISSUE THREAD

**Issue by HeadR123** [seriousm4x/UpSnap#70]
**Describe the bug**
Its possible to upload a new icon and its shown in the settings but as soon as you press save the icon disappears in the settings and where Gopher was seen is only a broken image shown. When tried to open the picture in another tab it shows "http://api/files/settings_public/qiitgg0zlmv5jh5/logo_gwpc_vektor_wa_an_ls2_sad_SvA38m7IY5.svg"

When i add the 172.30.9.130:8080/ in front (like: http://172.30.9.130:8080/api/files/settings_public/qiitgg0zlmv5jh5/logo_gwpc_vektor_wa_an_ls2_sad_SvA38m7IY5.svg)  it shows the image.

**To Reproduce**
Change icon

**Expected behavior**
New Logo should be shown in the top left corner.

**Screenshots**

![image](https://user-images.githubusercontent.com/47114328/231417633-9a42d0b7-98b1-47a5-9c67-716bcf50a20a.png)

![image](https://user-images.githubusercontent.com/47114328/231417915-4e27242c-8048-40b4-8e20-68ffe9ac09c0.png)

**Host OS (and version)**
Ubuntu 22.10

**Brower (if relevant)**
Chrome Version 111.0.5563.147

**Comment by seriousm4x** [comment]
Thanks
