### ISSUE TITLE
[REQUEST] add i18n support

### ISSUE THREAD

**Issue by XlangNan** [seriousm4x/UpSnap#71]
很喜欢这个项目，希望增加中文支持

**Comment by seriousm4x** [comment]
Every string is available in **english** and **german**. These are the only languages i know.
I will put a *How to add translations* into the wiki in the next days.

Language defaults to the browser language with fallback to english if no translation exists. On the account edit page you can choose your prefered language as well, which will overwrite the default language.

![image](https://github.com/seriousm4x/UpSnap/assets/23456686/ee10db98-f956-4eaa-94d6-4369029686cb)

**Comment by seriousm4x** [comment]
Here is the wiki page https://github.com/seriousm4x/UpSnap/wiki/Ho-to-add-languages
