### ISSUE TITLE
Using the REST API with curl to send WOL

### ISSUE THREAD

**Issue by bnhf** [seriousm4x/UpSnap#74]
I've been messing around with this for a bit with no success, so thought I would reach out for some assistance. :-)

I'd imagine there's a fairly straightforward way to use curl to get the jwt token and then send a WOL request to one of my registered devices in UpSnap. A little help with the proper syntax would be appreciated!

**Comment by seriousm4x** [comment]
Have you checked the [wiki](https://github.com/seriousm4x/UpSnap/wiki/Rest-API)?

**Comment by bnhf** [comment]
@seriousm4x 

> Have you checked the [wiki](https://github.com/seriousm4x/UpSnap/wiki/Rest-API)?

I have, but I can't seem to come up with the right syntax to request a token and then use it for WOL in a one line curl. Any chance you could point me in the right direction, or shoot me an example using curl?

**Comment by bnhf** [comment]
@seriousm4x 

OK, so I finally got the token using:

```console
curl -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' --data '{"identity":"<myusernamehere>","password":"<mypasswordhere>","rememberMe":false}' http://apcupsd:8090/api/admins/auth-with-password
```

Now we'll see if I can expand it to include the WOL portion in the same command...

**Comment by bnhf** [comment]
@seriousm4x 

I have a curl one-liner that's working, that I'll use, unless you know of a cleaner way to do it:

```console
curl -H 'Accept: application/json' -H "Authorization: Bearer $(curl -s -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' --data '{"identity":"<myusernamehere>","password":"<mypasswordhere>","rememberMe":false}' http://apcupsd:8090/api/admins/auth-with-password | jq -r '.token')" http://apcupsd:8090/api/upsnap/wake/:<mydeviceidhere>
```

Having a curl example like this, and perhaps an http:// based example that someone could use as a bookmarkable URL to wake a machine could be nice additions to the Wiki.

**Comment by seriousm4x** [comment]
if you need a one liner I thinks that's the same solution I would have come up with as well. Basically you need to get the token first and then send the token with every other request you need to make. Just like you did.

You might want to test what happens, when the nested curl command for the token fails.
