### ISSUE TITLE
[REQUEST] Device access permissions per user 

### ISSUE THREAD

**Issue by rpiastowski** [seriousm4x/UpSnap#75]
**Very cool application!**

It would be nice if you could assign **device permissions per user**. So that a given user can only see devices that he allows.
Currently, all users can see all devices, and I would like to assign a given user to see only selected devices, and e.g. admins to see all devices.

**Comment by javijuji** [comment]
This would be great. Same requierement here. Wifes PC has been racked and want her to be able to wol her own device only.

**Comment by seriousm4x** [comment]
I'm done implementing this. Here is a quick preview screenshot:
![image](https://github.com/seriousm4x/UpSnap/assets/23456686/a8dc4348-eb28-45d9-a60b-93c45854eb4f)
Will be ready to test with the first beta release of upsnap 4

**Comment by seriousm4x** [comment]
First beta is available now: [4.0.0-beta.1](https://github.com/seriousm4x/UpSnap/releases/tag/4.0.0-beta.1)
Would really help me if you guys could test it!
