### ISSUE TITLE
Sleep on LAN

### ISSUE THREAD

**Issue by silkyclouds** [seriousm4x/UpSnap#78]
The title says it all. Could you please add SOL to upsnap ? I love it, I don't want to use anything else. 

SOL can be enabled by installing a little app on the remote computers.

This project does it (but there is no proper login screen, nor a nice looking webUIto add devices...) : 

https://github.com/ex0nuss/Remote-Wake-Sleep-On-LAN-Docker

THANKS ! :)

**Comment by seriousm4x** [comment]
Depending on what Sleep On Lan program you use, you can already do so. You can just use curl with the sleep url as the shutdown command.

For example if you use https://github.com/SR-G/sleep-on-lan#sleep-through-rest-service
You can set the `Shutdown Cmd` inside the device settings to `curl http://192.168.8.4:8009/sleep/`

**Comment by silkyclouds** [comment]
Oh nice I didn't know that there were SOL client reacting to a curl command. Cool ! I'm trying this right away ! Thanks ! :)
