### ISSUE TITLE
doesnt work for me

### ISSUE THREAD

**Issue by e-p-s** [seriousm4x/UpSnap#8]
Thanks for this project.

Unfortunately, it does not work for me. Neither in Proxmox LXC nor in VM mode.
If i try etherwake or wakeonlan command line tool, its works in both

i use default docker-compose.yml

```root@UpSnap:~# cat docker-compose.yml
version: "3"
services:
  upsnap_django:
    container_name: upsnap_django
    image: seriousm4x/upsnap:latest
    network_mode: host
    restart: unless-stopped
    environment:
      - DJANGO_SUPERUSER_USER=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SECRET_KEY=secret
      - DJANGO_DEBUG=False
      - DJANGO_LANGUAGE_CODE=de
      - DJANGO_TIME_ZONE=Europe/Berlin
      - DJANGO_PORT=80
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
      - DB_TYPE=sqlite
      - PING_INTERVAL=5
      - ENABLE_NOTIFICATIONS=True
    depends_on:
      - upsnap_redis
  upsnap_redis:
    container_name: upsnap_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 10s
`

Backup looks like this:

`{
    "30:9C:23:DB:90:D2": {
        "name": "PC-MAIN",
        "ip": "172.30.60.101",
        "netmask": "255.255.255.0"
    },
    "00:08:9b:db:09:ce": {
        "name": "NAS4",
        "ip": "172.30.70.4",
        "netmask": "255.255.255.0"
    },
    "00:11:32:5d:00:ca": {
        "name": "NAS1",
        "ip": "172.30.70.1",
        "netmask": "255.255.255.0"
    },
    "5c:f4:ab:5e:90:3f": {
        "name": "NAS2",
        "ip": "172.30.70.2",
        "netmask": "255.255.255.0"
    },
    "00:08:9b:c0:4c:e5": {
        "name": "QNAP-NAS (Backup)",
        "ip": "172.30.70.101",
        "netmask": "255.255.255.0"
    }
}```

//Edit//
Code formating here in preview looks okay :(

**Comment by seriousm4x** [comment]
Looking at the json backup it seems like you are using the wrong netmask. Default netmask is 255.255.255.0 but you need 255.255.0.0 for you ips. I have to add it to the frontend to change the netmask there.

For now, you can either change it in the json and import it again or on the website go to /admin, login with your superuser credentials and change it there.

(btw you can format code blocks with 3x ` )

**Comment by e-p-s** [comment]
thanks for answer

in the gui i set up:
Network address for discovering devices: 172.30.0.0/16

and under devices, there is no point to change the mask :)

but yes. i saw it in the backup, though this must be.
i'll give it a try

**Comment by seriousm4x** [comment]
Yes, I still have to add this function to change the netmask. Default to 255.255.255.0 won't work for other ranges.
