### ISSUE TITLE
[REQUEST] Show WoL Execute Log On screen or debug mode ?

### ISSUE THREAD

**Issue by Nebulosa-Cat** [seriousm4x/UpSnap#80]
When i use this project it was easy to build and work great. 
The main problem is, when I shutdown computer and immediately WoL it will work, but after night it will fail to wakeup computer (windows).

The system is windows11，and network device is onboard intel i225v，bios and in system setting already checked, and because it was only happen when it power off after night so i can't use traditional way (wireshark) to debug it.

So the best way maybe look the work log flow when use WoL, but i'm not sure the way normal wakeonlan command are same as this project use. So maybe have a debug mode or a show log option is better for this kind of debug use case ?

**Comment by seriousm4x** [comment]
Sounds like your router will drop the mac address after some time when your pc is offline. You can try and check if your router/switch still shows your pc if wake on lan isn't working anymore.

Maxbe this forum post will help you: https://forums.tomshardware.com/threads/why-does-wake-on-wan-stop-working-after-a-while.1897437/#post-13127191

This project sends the default magic packet via udp to port 9. This is the default for every wol program.

It's difficult to show any more debug logs, as there is no response after sending a magic packet. It just gets send and never receives an answer from hosts. So debugging why your pc won't wake is basically up to you.

**Comment by seriousm4x** [comment]
If you have another pc on the network, you can try to find out if it is your pc or the router. Either way, feel free to reopen if it's actually an issue with this project.
