### ISSUE TITLE
[BUG] UNIQUE constraint failed

### ISSUE THREAD

**Issue by sirnicolas21** [seriousm4x/UpSnap#922]
getting this while deploying, used portainer with and without privs

Error: Failed to apply migration 1735377462_collections_snapshot.go: failed to save collection "users": constraint failed: UNIQUE constraint failed: _collections.name (2067)

![image](https://github.com/user-attachments/assets/c80e7899-8493-4c4b-bb53-3063d3dfd68a)

![image](https://github.com/user-attachments/assets/59859b5b-a8ea-4536-9727-92ef3ed08804)

![image](https://github.com/user-attachments/assets/e25239b8-8591-41b8-87eb-2c0573a089bb)

### The OS that UpSnap is running on

UnRaid

### Version of UpSnap

latest

### Your docker-compose.yml content

```YAML
not applicable
```

### Reproduction steps

```bash
install from UnRaid community or from portainer
```

**Comment by seriousm4x** [comment]
I tried replicating this error but I'm not able to. My database upgrades successfully from version 4.3.4 to 4.4.0.

Some troubleshooting questions:
- What version did you guys use before? To make all migrations work seamlessly, please upgrade to version 4.3.4 and then 4.4.0. I had to wipe all old database migrations for the latest release.
- Did you change any settings in the pocketbase backend at `http://localhost:8090/_/` which might lead to database migration errors?
- Is anyone willing to zip their database and send it to me? Either here on github or mail to `maxi[at]quoss[dot]org`.

**Comment by sirnicolas21** [comment]
I am a new user, nothing was installed before, so no database, nothing changed from default values

**Comment by Ellessm** [comment]
I am having the same issue. I am also a new user with no prior installation or database. I am trying to deploy upsnap in a docker container on a rpi 4 running the 64 bit Debian OS. Using the default values from the docker-compose.yml leads me to the same error in the portainer logs as OP. The container never publishes to a port. 

Error received:
Error: Failed to apply migration 1735377462_collections_snapshot.go: failed to save collection "users": constraint failed: UNIQUE constraint failed: _collections.name (2067)
